import { describe, it, expect, vi } from 'vitest'
import {
  BadRequestException,
  ForbiddenException,
  NotFoundException,
  UnprocessableEntityException,
} from '@nestjs/common'
import { ReleaseService, type ReleaseRequest } from './release.service'

type SkillCode = string

interface MockOperator {
  id: string
  badge: string
  skills: SkillCode[]
}

interface MockStep {
  id: string
  groupId: string
  order: number
  category: string
  actionType: string
  type: string
  source: string
  name: string
  instructions: string | null
  skillId: string | null
  deviceId: string | null
  recipeId: string | null
  toolId: string | null
  standardTimeSec: number | null
  isRequired: boolean
  partReference: string | null
  noTargetPolicy: string | null
  deviceCategory: string | null
}

interface MockWorkflow {
  id: string
  plantId: string
  currentVersionId: string | null
  workflowVersions: Array<{
    id: string
    workflowId: string
    version: number
    status: string
    notes: string | null
    phases: Array<{
      id: string
      workflowVersionId: string
      order: number
      category: string
      name: string
      isCycleBased: boolean
      isAutoGenerated: boolean
      description: string | null
      groups: Array<{
        id: string
        phaseId: string
        order: number
        category: string
        name: string
        supportsParallel: boolean
        supportsRecovery: boolean
        isAutoGenerated: boolean
        description: string | null
        steps: MockStep[]
      }>
    }>
  }>
}

const buildStep = (
  id: string,
  groupId: string,
  order: number,
  over: Partial<MockStep> = {},
): MockStep => ({
  id,
  groupId,
  order,
  category: 'production',
  actionType: 'NORMAL',
  type: 'normal',
  source: 'manual',
  name: `Step ${id}`,
  instructions: null,
  skillId: null,
  deviceId: null,
  recipeId: null,
  toolId: null,
  standardTimeSec: 30,
  isRequired: true,
  partReference: null,
  noTargetPolicy: null,
  deviceCategory: null,
  ...over,
})

const buildWorkflow = (over: Partial<MockWorkflow> = {}): MockWorkflow => {
  const wf: MockWorkflow = {
    id: 'wf-1',
    plantId: 'plant-1',
    currentVersionId: 'wfv-1',
    workflowVersions: [
      {
        id: 'wfv-1',
        workflowId: 'wf-1',
        version: 2,
        status: 'approved',
        notes: null,
        phases: [
          {
            id: 'phase-1',
            workflowVersionId: 'wfv-1',
            order: 1,
            category: 'production',
            name: 'Production',
            isCycleBased: false,
            isAutoGenerated: false,
            description: null,
            groups: [
              {
                id: 'group-1-1',
                phaseId: 'phase-1',
                order: 1,
                category: 'device_execution',
                name: 'Extrusion',
                supportsParallel: false,
                supportsRecovery: true,
                isAutoGenerated: false,
                description: null,
                steps: [
                  buildStep('step-1', 'group-1-1', 1),
                  buildStep('step-2', 'group-1-1', 2),
                  buildStep('step-3', 'group-1-1', 3),
                ],
              },
            ],
          },
        ],
      },
    ],
    ...over,
  }
  return wf
}

interface ServiceMocks {
  manager?: MockOperator | null
  workflow?: MockWorkflow | null
  item?: { id: string } | null
  assignedOperator?: MockOperator | null
  shift?: { id: string } | null
  woCount?: number
  txWoId?: string
  txSnapshotId?: string
}

function makeService(opts: ServiceMocks = {}) {
  const operatorFindFirst = vi.fn().mockImplementation(
    (args: { where?: { id?: string }; include?: unknown; select?: unknown }) => {
      const includesSkills =
        !!args?.include &&
        typeof args.include === 'object' &&
        'operatorSkills' in (args.include as Record<string, unknown>)
      if (includesSkills) {
        if (!opts.manager) return Promise.resolve(null)
        return Promise.resolve({
          id: opts.manager.id,
          badge: opts.manager.badge,
          operatorSkills: opts.manager.skills.map((code) => ({
            skill: { code },
          })),
        })
      }
      // assigned operator check
      if (!opts.assignedOperator) return Promise.resolve(null)
      return Promise.resolve({
        id: opts.assignedOperator.id,
        badge: opts.assignedOperator.badge,
      })
    },
  )

  const workflowFindFirst = vi.fn().mockResolvedValue(opts.workflow ?? null)
  const itemFindFirst = vi.fn().mockResolvedValue(opts.item ?? null)
  const shiftFindFirst = vi.fn().mockResolvedValue(opts.shift ?? null)
  const workOrderCount = vi.fn().mockResolvedValue(opts.woCount ?? 0)

  const woCreate = vi.fn().mockImplementation(({ data }: { data: { code: string; itemId: string } }) =>
    Promise.resolve({
      id: opts.txWoId ?? 'wo-new',
      code: data.code,
      itemId: data.itemId,
    }),
  )
  const snapshotCreate = vi
    .fn()
    .mockImplementation(({ data }: { data: { workOrderId: string } }) =>
      Promise.resolve({
        id: opts.txSnapshotId ?? 'snap-new',
        workOrderId: data.workOrderId,
      }),
    )
  const stepExecCreateMany = vi.fn().mockImplementation(({ data }: { data: unknown[] }) =>
    Promise.resolve({ count: data.length }),
  )
  const woAssignmentCreate = vi
    .fn()
    .mockResolvedValue({ id: 'asg-new', status: 'accepted' })
  const shiftAssignmentUpsert = vi
    .fn()
    .mockResolvedValue({ id: 'sa-new' })

  const txClient = {
    workOrder: { create: woCreate },
    workflowSnapshot: { create: snapshotCreate },
    stepExecution: { createMany: stepExecCreateMany },
    workOrderAssignment: { create: woAssignmentCreate },
    shiftAssignment: { upsert: shiftAssignmentUpsert },
  }

  const transaction = vi
    .fn()
    .mockImplementation((cb: (tx: typeof txClient) => unknown) => cb(txClient))

  const prisma = {
    operator: { findFirst: operatorFindFirst },
    workflow: { findFirst: workflowFindFirst },
    item: { findFirst: itemFindFirst },
    shift: { findFirst: shiftFindFirst },
    workOrder: { count: workOrderCount },
    $transaction: transaction,
  } as unknown as ConstructorParameters<typeof ReleaseService>[0]

  const recordMock = vi.fn().mockResolvedValue(undefined)
  const auditLog = {
    record: recordMock,
  } as unknown as ConstructorParameters<typeof ReleaseService>[1]

  const emitReleasedMock = vi.fn()
  const emitAssignedMock = vi.fn()
  const events = {
    emitWoReleased: emitReleasedMock,
    emitWoAssigned: emitAssignedMock,
    emitStepTransition: vi.fn(),
    emitParallelSync: vi.fn(),
  } as unknown as ConstructorParameters<typeof ReleaseService>[2]

  const service = new ReleaseService(prisma, auditLog, events)
  return {
    service,
    operatorFindFirst,
    workflowFindFirst,
    itemFindFirst,
    shiftFindFirst,
    workOrderCount,
    transaction,
    woCreate,
    snapshotCreate,
    stepExecCreateMany,
    woAssignmentCreate,
    shiftAssignmentUpsert,
    recordMock,
    emitReleasedMock,
    emitAssignedMock,
  }
}

const baseRequest = (over: Partial<ReleaseRequest> = {}): ReleaseRequest => ({
  workflowId: 'wf-1',
  itemId: 'item-1',
  quantity: 50,
  assignedOperatorId: 'op-2',
  releasedBy: 'op-mgr',
  plantId: 'plant-1',
  ...over,
})

describe('ReleaseService.release — happy path', () => {
  it('creates WO, snapshot, step executions, assignment; audits; emits events', async () => {
    const mocks = makeService({
      manager: { id: 'op-mgr', badge: 'OP-001', skills: ['MANAGER'] },
      workflow: buildWorkflow(),
      item: { id: 'item-1' },
      assignedOperator: { id: 'op-2', badge: 'OP-002', skills: [] },
    })
    const result = await mocks.service.release(baseRequest())
    expect(result.workOrderId).toBe('wo-new')
    expect(result.workOrderCode).toMatch(/^WO-\d{8}-001$/)
    expect(result.snapshotId).toBe('snap-new')
    expect(result.stepExecutionCount).toBe(3)
    expect(mocks.woCreate).toHaveBeenCalledOnce()
    expect(mocks.snapshotCreate).toHaveBeenCalledOnce()
    expect(mocks.stepExecCreateMany).toHaveBeenCalledOnce()
    expect(mocks.woAssignmentCreate).toHaveBeenCalledOnce()
    expect(mocks.shiftAssignmentUpsert).not.toHaveBeenCalled()
    expect(mocks.recordMock).toHaveBeenCalledOnce()
    expect(mocks.emitReleasedMock).toHaveBeenCalledOnce()
    expect(mocks.emitAssignedMock).toHaveBeenCalledOnce()
  })

  it('emits wo:released and wo:assigned with correct payloads', async () => {
    const mocks = makeService({
      manager: { id: 'op-mgr', badge: 'OP-001', skills: ['MANAGER'] },
      workflow: buildWorkflow(),
      item: { id: 'item-1' },
      assignedOperator: { id: 'op-2', badge: 'OP-002', skills: [] },
    })
    await mocks.service.release(baseRequest())
    const releasedCall = mocks.emitReleasedMock.mock.calls[0]?.[0]
    expect(releasedCall).toMatchObject({
      workOrderId: 'wo-new',
      releasedBy: 'op-mgr',
    })
    expect(releasedCall.code).toMatch(/^WO-\d{8}-001$/)
    expect(typeof releasedCall.releasedAt).toBe('string')

    const assignedCall = mocks.emitAssignedMock.mock.calls[0]?.[0]
    expect(assignedCall).toMatchObject({
      workOrderId: 'wo-new',
      operatorId: 'op-2',
    })
    expect(assignedCall.code).toMatch(/^WO-\d{8}-001$/)
  })

  it('persists snapshot JSON containing all source step IDs', async () => {
    const mocks = makeService({
      manager: { id: 'op-mgr', badge: 'OP-001', skills: ['MANAGER'] },
      workflow: buildWorkflow(),
      item: { id: 'item-1' },
      assignedOperator: { id: 'op-2', badge: 'OP-002', skills: [] },
    })
    await mocks.service.release(baseRequest())
    const snapData = mocks.snapshotCreate.mock.calls[0]?.[0]?.data
      ?.snapshotData as string
    expect(typeof snapData).toBe('string')
    const parsed = JSON.parse(snapData)
    expect(parsed.workflowVersionNumber).toBe(2)
    expect(parsed.status).toBe('approved')
    expect(parsed.phases[0].groups[0].steps.map((s: { id: string }) => s.id)).toEqual([
      'step-1',
      'step-2',
      'step-3',
    ])
    const seData = mocks.stepExecCreateMany.mock.calls[0]?.[0]?.data as Array<{
      stepId: string
      status: string
    }>
    expect(seData.map((s) => s.stepId)).toEqual(['step-1', 'step-2', 'step-3'])
    expect(seData.every((s) => s.status === 'pending')).toBe(true)
  })

  it('writes WorkOrder.actualStart=null and status=released (Q4)', async () => {
    const mocks = makeService({
      manager: { id: 'op-mgr', badge: 'OP-001', skills: ['MANAGER'] },
      workflow: buildWorkflow(),
      item: { id: 'item-1' },
      assignedOperator: { id: 'op-2', badge: 'OP-002', skills: [] },
    })
    await mocks.service.release(baseRequest())
    const woData = mocks.woCreate.mock.calls[0]?.[0]?.data as {
      actualStart: Date | null
      status: string
      qtyTarget: number
      releasedAt: Date
    }
    expect(woData.actualStart).toBeNull()
    expect(woData.status).toBe('released')
    expect(woData.qtyTarget).toBe(50)
    expect(woData.releasedAt).toBeInstanceOf(Date)
  })

  it('uses sequence WO-YYYYMMDD-002 when 1 prior WO exists same day', async () => {
    const mocks = makeService({
      manager: { id: 'op-mgr', badge: 'OP-001', skills: ['MANAGER'] },
      workflow: buildWorkflow(),
      item: { id: 'item-1' },
      assignedOperator: { id: 'op-2', badge: 'OP-002', skills: [] },
      woCount: 1,
    })
    const result = await mocks.service.release(baseRequest())
    expect(result.workOrderCode).toMatch(/^WO-\d{8}-002$/)
  })

  it('creates ShiftAssignment when assignedShiftId provided', async () => {
    const mocks = makeService({
      manager: { id: 'op-mgr', badge: 'OP-001', skills: ['MANAGER'] },
      workflow: buildWorkflow(),
      item: { id: 'item-1' },
      assignedOperator: { id: 'op-2', badge: 'OP-002', skills: [] },
      shift: { id: 'shift-1' },
    })
    await mocks.service.release(baseRequest({ assignedShiftId: 'shift-1' }))
    expect(mocks.shiftAssignmentUpsert).toHaveBeenCalledOnce()
  })

  it('audit log records release action with snapshot + WO metadata', async () => {
    const mocks = makeService({
      manager: { id: 'op-mgr', badge: 'OP-001', skills: ['MANAGER'] },
      workflow: buildWorkflow(),
      item: { id: 'item-1' },
      assignedOperator: { id: 'op-2', badge: 'OP-002', skills: [] },
    })
    await mocks.service.release(baseRequest())
    const audit = mocks.recordMock.mock.calls[0]?.[0] as {
      entityType: string
      action: string
      after: Record<string, unknown>
    }
    expect(audit.entityType).toBe('WorkOrder')
    expect(audit.action).toBe('state_change')
    expect(audit.after.action).toBe('release')
    expect(audit.after.snapshotId).toBe('snap-new')
    expect(audit.after.workflowVersionNumber).toBe(2)
    expect(audit.after.stepExecutionCount).toBe(3)
  })
})

describe('ReleaseService.release — RBAC + validation failures', () => {
  it('rejects with 403 when caller lacks MANAGER skill', async () => {
    const mocks = makeService({
      manager: { id: 'op-mgr', badge: 'OP-001', skills: ['EXT', 'QC'] },
      workflow: buildWorkflow(),
      item: { id: 'item-1' },
      assignedOperator: { id: 'op-2', badge: 'OP-002', skills: [] },
    })
    await expect(mocks.service.release(baseRequest())).rejects.toBeInstanceOf(
      ForbiddenException,
    )
    expect(mocks.transaction).not.toHaveBeenCalled()
  })

  it('rejects with 403 when caller operator not found in plant', async () => {
    const mocks = makeService({
      manager: null,
      workflow: buildWorkflow(),
      item: { id: 'item-1' },
      assignedOperator: { id: 'op-2', badge: 'OP-002', skills: [] },
    })
    await expect(mocks.service.release(baseRequest())).rejects.toBeInstanceOf(
      ForbiddenException,
    )
  })

  it('rejects with 404 when workflow not found', async () => {
    const mocks = makeService({
      manager: { id: 'op-mgr', badge: 'OP-001', skills: ['MANAGER'] },
      workflow: null,
      item: { id: 'item-1' },
      assignedOperator: { id: 'op-2', badge: 'OP-002', skills: [] },
    })
    await expect(mocks.service.release(baseRequest())).rejects.toBeInstanceOf(
      NotFoundException,
    )
  })

  it('rejects with 422 when workflow currentVersion is not approved', async () => {
    const draft = buildWorkflow()
    const v = draft.workflowVersions[0]
    if (v) v.status = 'draft'
    const mocks = makeService({
      manager: { id: 'op-mgr', badge: 'OP-001', skills: ['MANAGER'] },
      workflow: draft,
      item: { id: 'item-1' },
      assignedOperator: { id: 'op-2', badge: 'OP-002', skills: [] },
    })
    await expect(mocks.service.release(baseRequest())).rejects.toBeInstanceOf(
      UnprocessableEntityException,
    )
  })

  it('rejects with 422 when workflow has no currentVersionId', async () => {
    const wf = buildWorkflow({ currentVersionId: null })
    const mocks = makeService({
      manager: { id: 'op-mgr', badge: 'OP-001', skills: ['MANAGER'] },
      workflow: wf,
      item: { id: 'item-1' },
      assignedOperator: { id: 'op-2', badge: 'OP-002', skills: [] },
    })
    await expect(mocks.service.release(baseRequest())).rejects.toBeInstanceOf(
      UnprocessableEntityException,
    )
  })

  it('rejects with 404 when item not found in plant', async () => {
    const mocks = makeService({
      manager: { id: 'op-mgr', badge: 'OP-001', skills: ['MANAGER'] },
      workflow: buildWorkflow(),
      item: null,
      assignedOperator: { id: 'op-2', badge: 'OP-002', skills: [] },
    })
    await expect(mocks.service.release(baseRequest())).rejects.toBeInstanceOf(
      NotFoundException,
    )
  })

  it('rejects with 404 when assigned operator not found in plant', async () => {
    const mocks = makeService({
      manager: { id: 'op-mgr', badge: 'OP-001', skills: ['MANAGER'] },
      workflow: buildWorkflow(),
      item: { id: 'item-1' },
      assignedOperator: null,
    })
    await expect(mocks.service.release(baseRequest())).rejects.toBeInstanceOf(
      NotFoundException,
    )
  })

  it('rejects with 404 when shiftId provided but shift not found', async () => {
    const mocks = makeService({
      manager: { id: 'op-mgr', badge: 'OP-001', skills: ['MANAGER'] },
      workflow: buildWorkflow(),
      item: { id: 'item-1' },
      assignedOperator: { id: 'op-2', badge: 'OP-002', skills: [] },
      shift: null,
    })
    await expect(
      mocks.service.release(baseRequest({ assignedShiftId: 'shift-x' })),
    ).rejects.toBeInstanceOf(NotFoundException)
  })

  it('rejects with 400 when quantity is zero or negative', async () => {
    const mocks = makeService({
      manager: { id: 'op-mgr', badge: 'OP-001', skills: ['MANAGER'] },
      workflow: buildWorkflow(),
      item: { id: 'item-1' },
      assignedOperator: { id: 'op-2', badge: 'OP-002', skills: [] },
    })
    await expect(
      mocks.service.release(baseRequest({ quantity: 0 })),
    ).rejects.toBeInstanceOf(BadRequestException)
    await expect(
      mocks.service.release(baseRequest({ quantity: -5 })),
    ).rejects.toBeInstanceOf(BadRequestException)
  })

  it('rejects with 400 when quantity is not an integer', async () => {
    const mocks = makeService({
      manager: { id: 'op-mgr', badge: 'OP-001', skills: ['MANAGER'] },
      workflow: buildWorkflow(),
      item: { id: 'item-1' },
      assignedOperator: { id: 'op-2', badge: 'OP-002', skills: [] },
    })
    await expect(
      mocks.service.release(baseRequest({ quantity: 1.5 })),
    ).rejects.toBeInstanceOf(BadRequestException)
  })
})
