import { Injectable, NotFoundException } from '@nestjs/common'
import { PrismaService } from '../prisma/prisma.service'

export type MineWorkOrderDto = {
  id: string
  code: string
  itemCode: string
  itemName: string
  quantity: number
  completed: number
  priority: 'low' | 'normal' | 'high'
  status: 'ready' | 'in_progress'
  startedAt: string | null
  shiftCode: string | null
}

// PROMPT_DESIGN_ALIGNMENT D3 batch 9 — back-office WO detail (mockup ScreenWODetail).
// Detail projection used by GET /work-orders/:id. Includes scalar WO fields, item +
// BoM lines, parsed snapshot phases (when present), step-execution counts, assignments
// and recent activity. Tabs that depend on backend data not yet built (multi-level
// timer, scrap-by-cause, full genealogy) are filled with sensible defaults — see
// page-level TODOs.
export type WorkOrderDetailDto = {
  id: string
  code: string
  status: string
  priority: string
  type: string
  qtyTarget: number
  qtyProduced: number
  qtyScrap: number
  qtyRework: number
  scheduledStart: string | null
  scheduledEnd: string | null
  actualStart: string | null
  actualEnd: string | null
  releasedAt: string | null
  releasedBy: string | null
  notes: string | null
  plantId: string
  createdAt: string
  updatedAt: string
  item: { id: string; code: string; name: string; uom: string }
  bom:
    | {
        id: string
        version: number
        lines: Array<{
          id: string
          componentCode: string
          componentName: string
          qty: number
          uom: string
        }>
      }
    | null
  workflowSnapshot: {
    id: string
    workflowVersionId: string
    snapshotData: WorkflowSnapshotProjection | null
    createdAt: string
  } | null
  assignments: Array<{
    operatorId: string
    operatorBadge: string
    operatorName: string
    status: string
    assignedAt: string
    acceptedAt: string | null
  }>
  stepExecutionStats: {
    total: number
    pending: number
    running: number
    done: number
    nok: number
  }
}

// Minimal projection of WorkflowSnapshot.snapshotData JSON. Mirrors the shape
// produced by @mes/domain cloneWorkflowTree but kept narrow so the SDK type
// surface stays stable even if the snapshot schema gains fields.
export type WorkflowSnapshotProjection = {
  workflowVersionNumber: number
  phases: Array<{
    id: string
    order: number
    category: string
    name: string
    isAutoGenerated: boolean
    imageUrl: string | null
    groups: Array<{
      id: string
      order: number
      category: string
      name: string
      isAutoGenerated: boolean
      steps: Array<{
        id: string
        order: number
        category: string
        actionType: string
        name: string
        deviceCategory: string | null
        partReference: string | null
        standardTimeSec: number | null
      }>
    }>
  }>
}

// AssignmentStatus values from packages/types/src/enums/work-order.enum.ts
// Active = post-acceptance, before completion. Declined/completed/proposed are excluded.
const ACTIVE_ASSIGNMENT_STATUSES = ['accepted', 'active']
const HIDDEN_WO_STATUSES = ['draft', 'closed', 'cancelled']

function startOfDay(d: Date): Date {
  return new Date(d.getFullYear(), d.getMonth(), d.getDate())
}

function endOfDay(d: Date): Date {
  return new Date(d.getFullYear(), d.getMonth(), d.getDate(), 23, 59, 59, 999)
}

function normalizePriority(p: string): MineWorkOrderDto['priority'] {
  return p === 'low' || p === 'high' ? p : 'normal'
}

function normalizeStatus(s: string): MineWorkOrderDto['status'] {
  return s === 'in_progress' ? 'in_progress' : 'ready'
}

@Injectable()
export class WorkOrdersService {
  constructor(private readonly prisma: PrismaService) {}

  async findMine(operatorId: string, now: Date = new Date()): Promise<MineWorkOrderDto[]> {
    const [assignments, todaysShift] = await Promise.all([
      this.prisma.workOrderAssignment.findMany({
        where: {
          operatorId,
          status: { in: ACTIVE_ASSIGNMENT_STATUSES },
        },
        include: {
          workOrder: { include: { item: true } },
        },
      }),
      this.prisma.shiftAssignment.findFirst({
        where: {
          operatorId,
          date: { gte: startOfDay(now), lte: endOfDay(now) },
        },
        include: { shift: true },
      }),
    ])

    const shiftCode = todaysShift?.shift.code ?? null

    return assignments
      .filter(
        (a) =>
          a.workOrder.deletedAt === null &&
          !HIDDEN_WO_STATUSES.includes(a.workOrder.status),
      )
      .map((a) => ({
        id: a.workOrder.id,
        code: a.workOrder.code,
        itemCode: a.workOrder.item.code,
        itemName: a.workOrder.item.name,
        quantity: a.workOrder.qtyTarget,
        completed: a.workOrder.qtyProduced,
        priority: normalizePriority(a.workOrder.priority),
        status: normalizeStatus(a.workOrder.status),
        startedAt: a.workOrder.actualStart?.toISOString() ?? null,
        shiftCode,
      }))
  }

  async findDetail(id: string): Promise<WorkOrderDetailDto> {
    const wo = await this.prisma.workOrder.findFirst({
      where: { id, deletedAt: null },
      include: {
        item: true,
        bom: { include: { lines: { orderBy: { position: 'asc' } } } },
        workflowSnapshot: true,
        assignments: { include: { operator: true }, orderBy: { assignedAt: 'desc' } },
      },
    })
    if (!wo) throw new NotFoundException(`Work order ${id} not found`)

    // BOMLine has no `component` relation in schema — fetch component items in
    // a single follow-up query to project code/name.
    const componentIds = wo.bom?.lines.map((l) => l.componentId) ?? []
    const components =
      componentIds.length === 0
        ? []
        : await this.prisma.item.findMany({
            where: { id: { in: componentIds } },
            select: { id: true, code: true, name: true },
          })
    const componentById = new Map(components.map((c) => [c.id, c]))

    const stepExecRows = await this.prisma.stepExecution.findMany({
      where: { workOrderId: id },
      select: { status: true, result: true },
    })

    const snapshotProjection = wo.workflowSnapshot
      ? parseSnapshotData(wo.workflowSnapshot.snapshotData)
      : null

    return {
      id: wo.id,
      code: wo.code,
      status: wo.status,
      priority: wo.priority,
      type: wo.type,
      qtyTarget: wo.qtyTarget,
      qtyProduced: wo.qtyProduced,
      qtyScrap: wo.qtyScrap,
      qtyRework: wo.qtyRework,
      scheduledStart: wo.scheduledStart?.toISOString() ?? null,
      scheduledEnd: wo.scheduledEnd?.toISOString() ?? null,
      actualStart: wo.actualStart?.toISOString() ?? null,
      actualEnd: wo.actualEnd?.toISOString() ?? null,
      releasedAt: wo.releasedAt?.toISOString() ?? null,
      releasedBy: wo.releasedBy,
      notes: wo.notes,
      plantId: wo.plantId,
      createdAt: wo.createdAt.toISOString(),
      updatedAt: wo.updatedAt.toISOString(),
      item: {
        id: wo.item.id,
        code: wo.item.code,
        name: wo.item.name,
        uom: wo.item.uom,
      },
      bom: wo.bom
        ? {
            id: wo.bom.id,
            version: wo.bom.version,
            lines: wo.bom.lines.map((l) => {
              const c = componentById.get(l.componentId)
              return {
                id: l.id,
                componentCode: c?.code ?? l.componentId,
                componentName: c?.name ?? '(componente sconosciuto)',
                qty: l.qty,
                uom: l.uom,
              }
            }),
          }
        : null,
      workflowSnapshot: wo.workflowSnapshot
        ? {
            id: wo.workflowSnapshot.id,
            workflowVersionId: wo.workflowSnapshot.workflowVersionId,
            snapshotData: snapshotProjection,
            createdAt: wo.workflowSnapshot.createdAt.toISOString(),
          }
        : null,
      assignments: wo.assignments.map((a) => ({
        operatorId: a.operatorId,
        operatorBadge: a.operator.badge,
        operatorName: `${a.operator.firstName} ${a.operator.lastName}`.trim(),
        status: a.status,
        assignedAt: a.assignedAt.toISOString(),
        acceptedAt: a.acceptedAt?.toISOString() ?? null,
      })),
      stepExecutionStats: aggregateStepStats(stepExecRows),
    }
  }
}

function aggregateStepStats(rows: Array<{ status: string; result: string | null }>): WorkOrderDetailDto['stepExecutionStats'] {
  let pending = 0
  let running = 0
  let done = 0
  let nok = 0
  for (const r of rows) {
    if (r.status === 'pending') pending++
    else if (r.status === 'running' || r.status === 'paused' || r.status === 'blocked' || r.status === 'qc_hold') running++
    else if (r.status === 'done' || r.status === 'recovered') done++
    if (r.result === 'nok') nok++
  }
  return { total: rows.length, pending, running, done, nok }
}

// Best-effort parser for WorkflowSnapshot.snapshotData (JSON). Unknown shapes
// degrade to null rather than throwing — the detail endpoint must keep working
// even if a legacy/malformed snapshot exists.
function parseSnapshotData(raw: string): WorkflowSnapshotProjection | null {
  try {
    const parsed = JSON.parse(raw) as unknown
    if (!parsed || typeof parsed !== 'object') return null
    const data = parsed as Record<string, unknown>
    const phasesRaw = Array.isArray(data['phases']) ? (data['phases'] as unknown[]) : []
    const phases = phasesRaw.map((p) => {
      const ph = p as Record<string, unknown>
      const groupsRaw = Array.isArray(ph['groups']) ? (ph['groups'] as unknown[]) : []
      return {
        id: String(ph['id'] ?? ''),
        order: Number(ph['order'] ?? 0),
        category: String(ph['category'] ?? ''),
        name: String(ph['name'] ?? ''),
        isAutoGenerated: Boolean(ph['isAutoGenerated']),
        imageUrl: ph['imageUrl'] != null ? String(ph['imageUrl']) : null,
        groups: groupsRaw.map((g) => {
          const gr = g as Record<string, unknown>
          const stepsRaw = Array.isArray(gr['steps']) ? (gr['steps'] as unknown[]) : []
          return {
            id: String(gr['id'] ?? ''),
            order: Number(gr['order'] ?? 0),
            category: String(gr['category'] ?? ''),
            name: String(gr['name'] ?? ''),
            isAutoGenerated: Boolean(gr['isAutoGenerated']),
            steps: stepsRaw.map((s) => {
              const st = s as Record<string, unknown>
              return {
                id: String(st['id'] ?? ''),
                order: Number(st['order'] ?? 0),
                category: String(st['category'] ?? ''),
                actionType: String(st['actionType'] ?? ''),
                name: String(st['name'] ?? ''),
                deviceCategory: st['deviceCategory'] != null ? String(st['deviceCategory']) : null,
                partReference: st['partReference'] != null ? String(st['partReference']) : null,
                standardTimeSec: st['standardTimeSec'] != null ? Number(st['standardTimeSec']) : null,
              }
            }),
          }
        }),
      }
    })
    return {
      workflowVersionNumber: Number(data['workflowVersionNumber'] ?? 1),
      phases,
    }
  } catch {
    return null
  }
}
