// PROMPT_PNE_2 D3 — Workflow v1 (Demo) for Pneumatic Air M12 680mm.
// PROMPT_PNE_SEED_CLEANUP (post F1 hotfix, 2026-05-03) — recovery redesign.
//
// Code:    wf-pneumatic-air-680-v1
// Status:  approved (PROMPT "Active" → schema enum 'approved')
// Item:    PNE-TUBE-12-680
// Tree:    4 phases / 7 groups (4 main + 2 recovery-refs + 1 conformity) / 30 step rows
//
// Post-cleanup recovery model (replaces inline REC-* sub-flow approach):
// - Recovery groups B2 (Leak) + C2 (Camera) now contain ONLY hidden ref steps
//   used as preRetryStepIds candidates from the workflow editor's
//   recoveryConfig section (D4.1 Automatic action form). They are NOT part of
//   the linear operator-facing flow; HMI page filters groups whose name
//   matches /Recovery/i from rendering and from the allTerminal computation.
// - The on-FAIL behaviour at runtime is owned by the RecoveryFlow inline
//   panel (D5, MAX_RECOVERY_ATTEMPTS=2 hardcoded). recoveryConfig persistence
//   on the Step row + DTO projection + HMI runtime read + pre-retry execution
//   are deferred to PROMPT_7 (TODO-040 extended). Until then the seed simply
//   exposes the refs to the editor; the modal does not consume them.
//
// New group C3 — Conformity Check holds STEP-CONFORMITY-001, a binary
// manual_choice (Conforme PASS / Non conforme NOK) that gates Imballaggio.
//
// Per S3 workaround: STEP-LEAK-003 (device main) encodes the 5-second parallel
// buffer in instructions text since the Group/Step schema lacks
// parallelStepsBufferSec column.
//
// The 10 fault codes (LK-* + CM-*) seeded by fault-codes.ts as CauseCode rows
// with category='recovery_fault' (D2) remain available for the HMIScrapForm
// dropdown in the recovery → scrap path.

import { SYSTEM, type PneumaticSeedContext, type Prisma } from '../helpers/upsert'

export const PNE_WORKFLOW_V1_CODE = 'wf-pneumatic-air-680-v1'
export const PNE_WORKFLOW_V1_NAME = 'Pneumatic Air M12 680mm v1 (Demo)'

interface StepDef {
  order: number
  name: string
  category: string // StepCategory
  actionType: string // StepActionType
  deviceCategory?: 'pre' | 'device_main' | 'parallel' | 'post' | null
  partReference?: 'current' | 'previous' | 'next' | 'previous_n' | 'batch' | 'none' | null
  instructions?: string
  skillCode?: string // resolves to ctx.skills[code].id
  deviceCode?: string // resolves to ctx.devices[code].id
  recipeCode?: string // resolves to ctx.recipes[code].id
  standardTimeSec?: number
  isRequired?: boolean
}

interface GroupDef {
  order: number
  category: string // GroupCategory
  name: string
  supportsParallel?: boolean
  supportsRecovery?: boolean
  isAutoGenerated?: boolean
  description?: string
  steps: StepDef[]
}

interface PhaseDef {
  order: number
  category: string // PhaseCategory
  name: string
  isCycleBased: boolean
  groups: GroupDef[]
}

// ─── Phase 1 — Final Assembly ──────────────────────────────────────────────
const PHASE_1: PhaseDef = {
  order: 1,
  category: 'production',
  name: 'Assemblaggio Finale',
  isCycleBased: true,
  groups: [
    {
      order: 1,
      category: 'assembly',
      name: 'A1 — Tube Preparation & Crimping',
      supportsParallel: false,
      supportsRecovery: false,
      steps: [
        { order: 1, name: '[1.1] Pick tube', category: 'production', actionType: 'assembly', skillCode: 'ASSY', standardTimeSec: 5 },
        { order: 2, name: '[1.2] Visual check tube condition', category: 'quality_control', actionType: 'visual_check', skillCode: 'QC', standardTimeSec: 4 },
        { order: 3, name: '[1.3] Mount raccordo end A (RACC-PNE-12-A)', category: 'production', actionType: 'assembly', skillCode: 'ASSY', standardTimeSec: 8 },
        { order: 4, name: '[1.4] Crimp end A', category: 'production', actionType: 'device_run', deviceCode: 'DEV-CRIMP-001', recipeCode: 'RCP-CRIMP-12-001', skillCode: 'ASSY', standardTimeSec: 8, instructions: '[AP-CRIMP-FORCE] Verificare forza crimpatura entro tolleranza ±1kN. Target 25kN.' },
        { order: 5, name: '[1.5] Visual check crimp A', category: 'quality_control', actionType: 'visual_check', skillCode: 'QC', standardTimeSec: 5 },
        { order: 6, name: '[1.6] Mount raccordo end B (RACC-PNE-12-B)', category: 'production', actionType: 'assembly', skillCode: 'ASSY', standardTimeSec: 8 },
        { order: 7, name: '[1.7] Crimp end B', category: 'production', actionType: 'device_run', deviceCode: 'DEV-CRIMP-001', recipeCode: 'RCP-CRIMP-12-001', skillCode: 'ASSY', standardTimeSec: 8, instructions: '[AP-CRIMP-FORCE] Verificare forza crimpatura entro tolleranza ±1kN. Target 25kN.' },
        { order: 8, name: '[1.8] Final visual check', category: 'quality_control', actionType: 'visual_check', skillCode: 'QC', standardTimeSec: 5 },
      ],
    },
  ],
}

// ─── Phase 2 — Leak Test (with inline recovery group B2) ───────────────────
const PHASE_2: PhaseDef = {
  order: 2,
  category: 'quality_control',
  name: 'Leak Test',
  isCycleBased: true,
  groups: [
    {
      order: 1,
      category: 'device_execution',
      name: 'B1 — Leak Test Execution',
      supportsParallel: true,
      supportsRecovery: true,
      description: 'Device execution con 3 step paralleli durante il ciclo 45s del leak tester.',
      steps: [
        // Pre
        { order: 1, name: '[STEP-LEAK-001] Position tube on fixture', category: 'setup', actionType: 'verify_workstation', deviceCategory: 'pre', skillCode: 'TEST', standardTimeSec: 8, instructions: '[AP-LEAK-PRESSURE] Disinnestare aria compressa prima di scollegare fixture.' },
        { order: 2, name: '[STEP-LEAK-002] Connect pneumatic hoses', category: 'setup', actionType: 'verify_tool', deviceCategory: 'pre', skillCode: 'TEST', standardTimeSec: 10 },
        // Device main
        { order: 3, name: '[STEP-LEAK-003] Run leak test cycle', category: 'production', actionType: 'device_run', deviceCategory: 'device_main', deviceCode: 'DEV-LEAK-001', recipeCode: 'RCP-LEAK-PNE-12-001', skillCode: 'TEST', standardTimeSec: 45, instructions: 'Cycle 45s @ 6.0 bar. parallelStepsBufferSec: 5 (S3 workaround — schema field absent). PASS < 0.5 mbar/min, MARGINAL 0.5-1.0, FAIL > 1.0.' },
        // Parallel children (during 45s device cycle)
        { order: 4, name: '[STEP-LEAK-004] Apply label LBL-PNE-001 on previous tube', category: 'identification', actionType: 'apply_label', deviceCategory: 'parallel', partReference: 'previous', skillCode: 'IDENTIFICATION', standardTimeSec: 12 },
        { order: 5, name: '[STEP-LEAK-005] Apply identification tape TAPE-IDENT-001 on previous tube', category: 'identification', actionType: 'apply_label', deviceCategory: 'parallel', partReference: 'previous', skillCode: 'IDENTIFICATION', standardTimeSec: 10 },
        { order: 6, name: '[STEP-LEAK-006] Prepare next tube on staging', category: 'production', actionType: 'assembly', deviceCategory: 'parallel', partReference: 'next', skillCode: 'ASSY', standardTimeSec: 20 },
        // Post
        { order: 7, name: '[STEP-LEAK-007] Read leak result', category: 'decision', actionType: 'manual_choice', deviceCategory: 'post', skillCode: 'TEST', standardTimeSec: 3, instructions: 'PASS → next step. MARGINAL → operator decision (re-test or escalate). FAIL → blocks the step; HMI RecoveryFlow inline panel (D5) opens with "Riprova" / "Scarta" buttons. After max attempts, HMIScrapForm modal collects cause code + photo + notes.' },
        { order: 8, name: '[STEP-LEAK-008] Disconnect hoses', category: 'teardown', actionType: 'verify_tool', deviceCategory: 'post', skillCode: 'TEST', standardTimeSec: 5 },
        { order: 9, name: '[STEP-LEAK-009] Remove tube to passed tray', category: 'logistics', actionType: 'move', deviceCategory: 'post', skillCode: 'IDENTIFICATION', standardTimeSec: 3 },
      ],
    },
    {
      order: 2,
      category: 'qc',
      name: 'B2 — Leak Recovery (refs)',
      supportsParallel: false,
      supportsRecovery: true,
      description: 'Hidden recovery refs only. Steps are exposed to the workflow editor as preRetryStepIds candidates for STEP-LEAK-003.recoveryConfig (D4.1 Automatic action form). HMI page.tsx filters this group from the linear operator flow via /Recovery/i name match. Pre-retry execution at runtime is deferred to PROMPT_7 (TODO-040).',
      steps: [
        { order: 1, name: '[STEP-LEAK-RECOVERY-CHECK] Verifica integrità tubo e sede', category: 'recovery', actionType: 'visual_check', skillCode: 'QC', standardTimeSec: 25, instructions: 'Ref step (recoveryConfig.preRetryStepIds candidate). Verifica visiva di integrità tubo, sede di tenuta, raccordi crimpati. Esposto al workflow editor; non eseguito nel flow lineare.' },
        { order: 2, name: '[STEP-LEAK-RECOVERY-CLEAN] Pulisci sede e riconnetti tubi', category: 'recovery', actionType: 'process', skillCode: 'QC', standardTimeSec: 40, instructions: 'Ref step (recoveryConfig.preRetryStepIds candidate). Pulizia sede di tenuta con isopropanolo, riconnessione tubi pneumatici, verifica serraggio.' },
      ],
    },
  ],
}

// ─── Phase 3 — Camera Test (with inline recovery group C2) ─────────────────
const PHASE_3: PhaseDef = {
  order: 3,
  category: 'quality_control',
  name: 'Camera Test',
  isCycleBased: true,
  groups: [
    {
      order: 1,
      category: 'device_execution',
      name: 'C1 — Optical Conformity Check',
      supportsParallel: false,
      supportsRecovery: true,
      steps: [
        { order: 1, name: '[3.1] Position tube in camera fixture', category: 'setup', actionType: 'verify_workstation', deviceCategory: 'pre', skillCode: 'TEST', standardTimeSec: 6 },
        { order: 2, name: '[3.2] Camera test cycle', category: 'production', actionType: 'device_run', deviceCategory: 'device_main', deviceCode: 'DEV-CAMERA-001', recipeCode: 'RCP-CAMERA-PNE-001', skillCode: 'TEST', standardTimeSec: 8, instructions: '4 ROIs (raccordo A, raccordo B, label, tape) — similarity threshold ≥ 95% per ROI.' },
        { order: 3, name: '[3.3] Read camera result', category: 'decision', actionType: 'manual_choice', deviceCategory: 'post', skillCode: 'TEST', standardTimeSec: 3, instructions: 'PASS → next step. FAIL → blocks the step; HMI RecoveryFlow inline panel (D5) opens with "Riprova" / "Scarta" buttons. After max attempts, HMIScrapForm modal collects cause code + photo + notes.' },
        { order: 4, name: '[3.4] Remove tube', category: 'logistics', actionType: 'move', deviceCategory: 'post', skillCode: 'IDENTIFICATION', standardTimeSec: 3 },
      ],
    },
    {
      order: 2,
      category: 'qc',
      name: 'C2 — Camera Recovery (refs)',
      supportsParallel: false,
      supportsRecovery: true,
      description: 'Hidden recovery refs only. Steps are exposed to the workflow editor as preRetryStepIds candidates for [3.2].recoveryConfig (D4.1 Automatic action form). HMI page.tsx filters this group from the linear operator flow via /Recovery/i name match. Pre-retry execution at runtime is deferred to PROMPT_7 (TODO-040).',
      steps: [
        { order: 1, name: '[STEP-CAM-RECOVERY-CLEAN] Pulisci lente e riposiziona pezzo', category: 'recovery', actionType: 'process', skillCode: 'QC', standardTimeSec: 30, instructions: 'Ref step (recoveryConfig.preRetryStepIds candidate). Pulizia lente camera con panno antistatico, ricontrollo illuminazione ring-light, riposizionamento tubo su fixture per SOP.' },
      ],
    },
    {
      order: 3,
      category: 'qc',
      name: 'C3 — Conformity Check',
      supportsParallel: false,
      supportsRecovery: false,
      description: 'Final QC gate before Imballaggio. Binary decision: Conforme (PASS, advance) / Non conforme (NOK, trigger HMIScrapForm with default cause "Non conformity at conformity check").',
      steps: [
        { order: 1, name: '[STEP-CONFORMITY-001] Conformity check', category: 'decision', actionType: 'manual_choice', skillCode: 'QC', standardTimeSec: 8, instructions: 'Operator binary choice: Conforme (PASS → next step Imballaggio) | Non conforme (NOK → opens HMIScrapForm modal pre-filled with cause "Non conformity at conformity check"). Rich variant taxonomy (estetico/funzionale/critico) deferred to post-demo.' },
      ],
    },
  ],
}

// ─── Phase 4 — Imballaggio (NOT cycle-based, sub-loops by box capacity) ────
const PHASE_4: PhaseDef = {
  order: 4,
  category: 'outbound',
  name: 'Imballaggio',
  isCycleBased: false,
  groups: [
    {
      order: 1,
      category: 'packaging',
      name: 'D1 — Box Management',
      supportsParallel: false,
      supportsRecovery: false,
      isAutoGenerated: true, // PROMPT § 3.2 AUTO-GEN tag
      description: 'Sub-loops by box capacity (50 tubi per BTYPE-PLT-RFA-001).',
      steps: [
        { order: 1, name: '[4.1] Select empty box BTYPE-PLT-RFA-001', category: 'logistics', actionType: 'select_empty_box', skillCode: 'IDENTIFICATION', standardTimeSec: 8 },
        { order: 2, name: '[4.2] Pack tube in box (scan serial, repeat 50×)', category: 'logistics', actionType: 'pack_into_box', skillCode: 'IDENTIFICATION', standardTimeSec: 6 },
        { order: 3, name: '[4.3] Validate box capacity reached (50 tubes)', category: 'quality_control', actionType: 'validate_box_capacity', skillCode: 'QC', standardTimeSec: 4 },
        { order: 4, name: '[4.4] Seal box', category: 'teardown', actionType: 'seal_box', skillCode: 'IDENTIFICATION', standardTimeSec: 10 },
        { order: 5, name: '[4.5] Print box label and apply', category: 'identification', actionType: 'print_box_label', skillCode: 'IDENTIFICATION', standardTimeSec: 12, instructions: '[AP-LABEL-LEGIBILITY] Verificare che marcatura sia leggibile prima di applicare etichetta.' },
      ],
    },
  ],
}

export const PNE_WORKFLOW_V1: { phases: PhaseDef[] } = {
  phases: [PHASE_1, PHASE_2, PHASE_3, PHASE_4],
}

// Aggregate counts (used by tests + STATUS docs)
export const PNE_WORKFLOW_V1_COUNTS = {
  phases: PNE_WORKFLOW_V1.phases.length,
  groups: PNE_WORKFLOW_V1.phases.reduce((sum, p) => sum + p.groups.length, 0),
  steps: PNE_WORKFLOW_V1.phases.reduce(
    (sum, p) => sum + p.groups.reduce((gsum, g) => gsum + g.steps.length, 0),
    0,
  ),
  recoveryGroups: PNE_WORKFLOW_V1.phases.reduce(
    (sum, p) => sum + p.groups.filter((g) => g.name.includes('Recovery')).length,
    0,
  ),
}

export async function seedWorkflowV1(
  prisma: Prisma,
  ctx: PneumaticSeedContext,
): Promise<{ workflowId: string; workflowVersionId: string }> {
  const item = ctx.items['PNE-TUBE-12-680']
  if (!item) throw new Error('Workflow v1 requires item PNE-TUBE-12-680 (must run D1 first)')

  // 1. Workflow
  const workflow = await prisma.workflow.upsert({
    where: { plantId_code: { plantId: ctx.plantId, code: PNE_WORKFLOW_V1_CODE } },
    update: { name: PNE_WORKFLOW_V1_NAME, itemId: item.id, updatedBy: SYSTEM },
    create: {
      code: PNE_WORKFLOW_V1_CODE,
      name: PNE_WORKFLOW_V1_NAME,
      itemId: item.id,
      description: 'Workflow demo Pneumatic Air M12 680mm — 4 fasi / 6 gruppi / 34 step. Cliente: Iveco/Volvo.',
      plantId: ctx.plantId,
      createdBy: SYSTEM,
      updatedBy: SYSTEM,
    },
  })

  // 2. WorkflowVersion v1 (status approved → PROMPT "Active")
  let version = await prisma.workflowVersion.findUnique({
    where: { workflowId_version: { workflowId: workflow.id, version: 1 } },
  })
  if (!version) {
    version = await prisma.workflowVersion.create({
      data: {
        workflowId: workflow.id,
        version: 1,
        status: 'approved',
        approvedBy: SYSTEM,
        approvedAt: new Date(),
        notes: 'Demo workflow seeded by PROMPT_PNE_2 D3.',
        createdBy: SYSTEM,
        updatedBy: SYSTEM,
      },
    })
  } else if (version.status !== 'approved') {
    version = await prisma.workflowVersion.update({
      where: { id: version.id },
      data: { status: 'approved', approvedBy: SYSTEM, approvedAt: new Date(), updatedBy: SYSTEM },
    })
  }
  if (workflow.currentVersionId !== version.id) {
    await prisma.workflow.update({
      where: { id: workflow.id },
      data: { currentVersionId: version.id, updatedBy: SYSTEM },
    })
  }

  // 3. Phases / Groups / Steps (idempotent by order within parent)
  for (const phaseDef of PNE_WORKFLOW_V1.phases) {
    let phase = await prisma.phase.findFirst({
      where: { workflowVersionId: version.id, order: phaseDef.order },
    })
    if (!phase) {
      phase = await prisma.phase.create({
        data: {
          workflowVersionId: version.id,
          order: phaseDef.order,
          category: phaseDef.category,
          name: phaseDef.name,
          isCycleBased: phaseDef.isCycleBased,
          createdBy: SYSTEM,
          updatedBy: SYSTEM,
        },
      })
    } else if (phase.name !== phaseDef.name || phase.category !== phaseDef.category || phase.isCycleBased !== phaseDef.isCycleBased) {
      await prisma.phase.update({
        where: { id: phase.id },
        data: { name: phaseDef.name, category: phaseDef.category, isCycleBased: phaseDef.isCycleBased, updatedBy: SYSTEM },
      })
    }

    for (const groupDef of phaseDef.groups) {
      let group = await prisma.group.findFirst({
        where: { phaseId: phase.id, order: groupDef.order },
      })
      if (!group) {
        group = await prisma.group.create({
          data: {
            phaseId: phase.id,
            order: groupDef.order,
            category: groupDef.category,
            name: groupDef.name,
            supportsParallel: groupDef.supportsParallel ?? false,
            supportsRecovery: groupDef.supportsRecovery ?? false,
            isAutoGenerated: groupDef.isAutoGenerated ?? false,
            description: groupDef.description ?? null,
            createdBy: SYSTEM,
            updatedBy: SYSTEM,
          },
        })
      } else {
        await prisma.group.update({
          where: { id: group.id },
          data: {
            name: groupDef.name,
            category: groupDef.category,
            supportsParallel: groupDef.supportsParallel ?? false,
            supportsRecovery: groupDef.supportsRecovery ?? false,
            isAutoGenerated: groupDef.isAutoGenerated ?? false,
            description: groupDef.description ?? null,
            updatedBy: SYSTEM,
          },
        })
      }

      for (const stepDef of groupDef.steps) {
        const skillId = stepDef.skillCode ? ctx.skills[stepDef.skillCode]?.id ?? null : null
        const deviceId = stepDef.deviceCode ? ctx.devices[stepDef.deviceCode]?.id ?? null : null
        const recipeId = stepDef.recipeCode ? ctx.recipes[stepDef.recipeCode]?.id ?? null : null

        const stepData = {
          order: stepDef.order,
          category: stepDef.category,
          actionType: stepDef.actionType,
          name: stepDef.name,
          instructions: stepDef.instructions ?? null,
          skillId,
          deviceId,
          recipeId,
          standardTimeSec: stepDef.standardTimeSec ?? null,
          isRequired: stepDef.isRequired ?? true,
          partReference: stepDef.partReference ?? null,
          deviceCategory: stepDef.deviceCategory ?? null,
        }

        const existing = await prisma.step.findFirst({
          where: { groupId: group.id, order: stepDef.order },
        })
        if (!existing) {
          await prisma.step.create({
            data: { ...stepData, groupId: group.id, createdBy: SYSTEM, updatedBy: SYSTEM },
          })
        } else {
          await prisma.step.update({
            where: { id: existing.id },
            data: { ...stepData, updatedBy: SYSTEM },
          })
        }
      }
    }
  }

  console.log(
    `✓ Workflow v1: ${PNE_WORKFLOW_V1_CODE} (${PNE_WORKFLOW_V1_COUNTS.phases} phases / ` +
      `${PNE_WORKFLOW_V1_COUNTS.groups} groups / ${PNE_WORKFLOW_V1_COUNTS.steps} steps; ` +
      `${PNE_WORKFLOW_V1_COUNTS.recoveryGroups} recovery-refs groups, hidden from linear flow)`,
  )
  return { workflowId: workflow.id, workflowVersionId: version.id }
}
