import { describe, it, expect, vi, beforeEach } from 'vitest'
import { render, screen, waitFor } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import * as React from 'react'

vi.mock('next/navigation', () => ({ useRouter: () => ({ push: vi.fn() }) }))
vi.mock('next/link', () => ({ default: ({ children, href }: { children: React.ReactNode; href: string }) =>
  React.createElement('a', { href }, children) }))

const workOrdersGet = vi.fn()
const workOrdersAudit = vi.fn()
vi.mock('../../../../lib/sdk', () => ({
  sdk: {
    workOrders: {
      get: (...a: unknown[]) => workOrdersGet(...a),
      audit: (...a: unknown[]) => workOrdersAudit(...a),
    },
  },
}))

import WorkOrderDetailPage from './page'

function renderWithQuery(ui: React.ReactElement) {
  const client = new QueryClient({ defaultOptions: { queries: { retry: false, gcTime: 0 } } })
  return render(<QueryClientProvider client={client}>{ui}</QueryClientProvider>)
}

const baseDetail = {
  id: 'wo-1',
  code: 'WO-2026-PNE-0042',
  status: 'in_progress',
  priority: 'high',
  type: 'production',
  qtyTarget: 100,
  qtyProduced: 42,
  qtyScrap: 2,
  qtyRework: 1,
  scheduledStart: '2026-04-30T06:00:00.000Z',
  scheduledEnd: '2026-05-01T14:00:00.000Z',
  actualStart: '2026-04-30T06:14:00.000Z',
  actualEnd: null,
  releasedAt: '2026-04-29T18:42:00.000Z',
  releasedBy: 'system',
  notes: 'Demo Pneumatic Air',
  plantId: 'plant_1',
  createdAt: '2026-04-29T14:00:00.000Z',
  updatedAt: '2026-04-30T07:00:00.000Z',
  item: { id: 'item-1', code: 'PNE-TUBE-12-680', name: 'Tubo PA12 12mm 680mm', uom: 'pc' },
  bom: {
    id: 'bom-1',
    version: 3,
    lines: [
      { id: 'l-1', componentCode: 'ITM-CMP-A', componentName: 'Componente A', qty: 2, uom: 'pc' },
    ],
  },
  workflowSnapshot: {
    id: 'snap-1',
    workflowVersionId: 'wfv-1',
    snapshotData: {
      workflowVersionNumber: 3,
      phases: [
        {
          id: 'p-1',
          order: 1,
          category: 'production',
          name: 'Estrusione',
          isAutoGenerated: false,
          groups: [
            {
              id: 'g-1',
              order: 1,
              category: 'main',
              name: 'Avvio linea',
              isAutoGenerated: false,
              steps: [
                {
                  id: 's-1',
                  order: 1,
                  category: 'identification',
                  actionType: 'scan_qr',
                  name: 'Scan ricetta',
                  deviceCategory: null,
                  partReference: null,
                  standardTimeSec: 30,
                },
              ],
            },
          ],
        },
      ],
    },
    createdAt: '2026-04-29T18:42:00.000Z',
  },
  assignments: [
    {
      operatorId: 'op-1',
      operatorBadge: '1234',
      operatorName: 'Mario Rossi',
      status: 'accepted',
      assignedAt: '2026-04-29T18:42:00.000Z',
      acceptedAt: '2026-04-30T05:55:00.000Z',
    },
  ],
  stepExecutionStats: { total: 168, pending: 50, running: 5, done: 110, nok: 3 },
}

beforeEach(() => {
  workOrdersGet.mockReset()
  workOrdersAudit.mockReset()
})

describe('WorkOrderDetailPage', () => {
  it('renders 7 tabs with execution count badge from stepExecutionStats.total', async () => {
    workOrdersGet.mockResolvedValue(baseDetail)
    renderWithQuery(<WorkOrderDetailPage params={{ id: 'wo-1' }} />)

    await waitFor(() => {
      expect(screen.getAllByText('WO-2026-PNE-0042').length).toBeGreaterThan(0)
    })

    // 7 tabs present
    expect(screen.getByRole('tab', { name: /Panoramica/ })).toBeInTheDocument()
    expect(screen.getByRole('tab', { name: /Snapshot workflow/ })).toBeInTheDocument()
    expect(screen.getByRole('tab', { name: /Materiali/ })).toBeInTheDocument()
    // Execution tab includes the count badge (168)
    expect(screen.getByRole('tab', { name: /Esecuzione.*168/ })).toBeInTheDocument()
    expect(screen.getByRole('tab', { name: /Qualità/ })).toBeInTheDocument()
    expect(screen.getByRole('tab', { name: /Genealogia/ })).toBeInTheDocument()
    expect(screen.getByRole('tab', { name: /Attività/ })).toBeInTheDocument()
  })

  it('Panoramica tab shows KPI cards with target/produced/scrap/rework + assignment + phase progress', async () => {
    workOrdersGet.mockResolvedValue(baseDetail)
    renderWithQuery(<WorkOrderDetailPage params={{ id: 'wo-1' }} />)

    await waitFor(() => {
      expect(screen.getAllByText('WO-2026-PNE-0042').length).toBeGreaterThan(0)
    })

    // KPI cards
    expect(screen.getByText('Target')).toBeInTheDocument()
    expect(screen.getByText('Prodotti')).toBeInTheDocument()
    expect(screen.getByText('Scarto')).toBeInTheDocument()
    expect(screen.getByText('Rilavorati')).toBeInTheDocument()

    // Operator name from assignments
    expect(screen.getByText(/Mario Rossi · 1234/)).toBeInTheDocument()

    // Phase from snapshot rendered in phase progress card
    expect(screen.getByText('Avanzamento per fase')).toBeInTheDocument()
    expect(screen.getByText('Estrusione')).toBeInTheDocument()
  })

  it('Snapshot workflow tab renders phase + group + step from parsed snapshotData', async () => {
    workOrdersGet.mockResolvedValue(baseDetail)
    renderWithQuery(<WorkOrderDetailPage params={{ id: 'wo-1' }} />)

    await waitFor(() => {
      expect(screen.getAllByText('WO-2026-PNE-0042').length).toBeGreaterThan(0)
    })

    screen.getByRole('tab', { name: /Snapshot workflow/ }).click()

    await waitFor(() => {
      expect(screen.getByText(/Snapshot bloccato al rilascio/)).toBeInTheDocument()
    })
    // Phase header (Estrusione appears both in Overview phase-progress and here)
    expect(screen.getAllByText('Estrusione').length).toBeGreaterThan(0)
    expect(screen.getByText('Avvio linea')).toBeInTheDocument()
    expect(screen.getByText('Scan ricetta')).toBeInTheDocument()
  })

  it('Materiali tab renders BoM line components with required/consumed derived from progress', async () => {
    workOrdersGet.mockResolvedValue(baseDetail)
    renderWithQuery(<WorkOrderDetailPage params={{ id: 'wo-1' }} />)

    await waitFor(() => {
      expect(screen.getAllByText('WO-2026-PNE-0042').length).toBeGreaterThan(0)
    })

    screen.getByRole('tab', { name: /Materiali/ }).click()

    await waitFor(() => {
      expect(screen.getByText('Componente A')).toBeInTheDocument()
    })
    // Required = qty(2) × qtyTarget(100) = 200
    expect(screen.getByText('200')).toBeInTheDocument()
    // Consumed = qty(2) × qtyProduced(42) = 84
    expect(screen.getByText('84')).toBeInTheDocument()
  })

  it('shows error message when WO not found', async () => {
    workOrdersGet.mockRejectedValue(new Error('not found'))
    renderWithQuery(<WorkOrderDetailPage params={{ id: 'missing' }} />)

    await waitFor(() => {
      expect(screen.getByText(/Ordine di lavoro non trovato/)).toBeInTheDocument()
    })
  })
})
