import { Injectable } from '@nestjs/common'
import { PrismaService } from '../prisma/prisma.service'
import { buildPaginatedResult } from '../../common/types/paginated'
import type { PaginatedResult } from '../../common/types/paginated'
import type { BaseFilters } from '../../common/base-registry.service'
import type { WorkflowPhaseInput } from '@mes/schemas'

// ── Flat model types ──────────────────────────────────────────────────────────

export type WorkflowModel = {
  id: string
  code: string
  name: string
  description: string | null
  itemId: string | null
  currentVersionId: string | null
  plantId: string
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  version: number
  createdBy: string
  updatedBy: string
}

export type WorkflowVersionModel = {
  id: string
  workflowId: string
  version: number
  status: string
  approvedBy: string | null
  approvedAt: Date | null
  notes: string | null
  createdAt: Date
  createdBy: string
  updatedAt: Date
  updatedBy: string
}

export type StepModel = {
  id: string
  groupId: string
  order: number
  category: string
  actionType: string
  type: string
  source: string
  name: string
  instructions: string | null
  skillId: string | null
  deviceId: string | null
  recipeId: string | null
  toolId: string | null
  standardTimeSec: number | null
  isRequired: boolean
  partReference: string | null
  noTargetPolicy: string | null
  /**
   * PROMPT_7 D1 — JSON-serialized polymorphic step data
   * (recoveryConfig + photoUrl + actionType). Consumers parse on demand —
   * mirrors StepExecution.data convention.
   */
  data: string | null
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
}

export type GroupModel = {
  id: string
  phaseId: string
  order: number
  category: string
  name: string
  description: string | null
  supportsParallel: boolean
  supportsRecovery: boolean
  isAutoGenerated: boolean
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  steps: StepModel[]
}

export type PhaseModel = {
  id: string
  workflowVersionId: string
  order: number
  category: string
  name: string
  description: string | null
  isCycleBased: boolean
  isAutoGenerated: boolean
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  groups: GroupModel[]
}

export type WorkflowVersionDetailModel = WorkflowVersionModel & {
  phases: PhaseModel[]
}

export type WorkflowDetailModel = WorkflowModel & {
  currentVersion: WorkflowVersionDetailModel | null
}

// ── Repository ────────────────────────────────────────────────────────────────

@Injectable()
export class WorkflowsRepository {
  constructor(private readonly prisma: PrismaService) {}

  async findAll(filters: BaseFilters): Promise<PaginatedResult<WorkflowModel>> {
    const where = {
      deletedAt: null as Date | null,
      ...(filters.plantId ? { plantId: filters.plantId } : {}),
      ...(filters.search
        ? {
            OR: [
              { code: { contains: filters.search } },
              { name: { contains: filters.search } },
            ],
          }
        : {}),
    }

    const orderBy: Record<string, 'asc' | 'desc'> = filters.sortBy
      ? { [filters.sortBy]: filters.sortDir ?? 'asc' }
      : { createdAt: 'desc' }

    const skip = (filters.page - 1) * filters.limit

    const [data, total] = await Promise.all([
      this.prisma.workflow.findMany({ where, orderBy, skip, take: filters.limit }),
      this.prisma.workflow.count({ where }),
    ])

    return buildPaginatedResult(data as WorkflowModel[], total, filters)
  }

  async findAllDeleted(filters: BaseFilters): Promise<PaginatedResult<WorkflowModel>> {
    const where = {
      deletedAt: { not: null as Date | null },
      ...(filters.plantId ? { plantId: filters.plantId } : {}),
    }

    const skip = (filters.page - 1) * filters.limit

    const [data, total] = await Promise.all([
      this.prisma.workflow.findMany({
        where,
        orderBy: { deletedAt: 'desc' },
        skip,
        take: filters.limit,
      }),
      this.prisma.workflow.count({ where }),
    ])

    return buildPaginatedResult(data as WorkflowModel[], total, filters)
  }

  async findDetailById(id: string): Promise<WorkflowDetailModel | null> {
    const workflow = await this.prisma.workflow.findFirst({
      where: { id, deletedAt: null },
    })

    if (!workflow) return null

    let currentVersion: WorkflowVersionDetailModel | null = null

    if (workflow.currentVersionId) {
      const ver = await this.prisma.workflowVersion.findUnique({
        where: { id: workflow.currentVersionId },
        include: {
          phases: {
            orderBy: { order: 'asc' },
            include: {
              groups: {
                orderBy: { order: 'asc' },
                include: {
                  steps: { orderBy: { order: 'asc' } },
                },
              },
            },
          },
        },
      })
      currentVersion = ver as WorkflowVersionDetailModel | null
    }

    return { ...(workflow as WorkflowModel), currentVersion }
  }

  async create(data: {
    code: string
    name: string
    description?: string | null
    itemId?: string | null
    plantId: string
    createdBy: string
  }): Promise<WorkflowDetailModel> {
    return this.prisma.$transaction(async (tx) => {
      const workflow = await tx.workflow.create({
        data: {
          code: data.code,
          name: data.name,
          description: data.description ?? null,
          itemId: data.itemId ?? null,
          plantId: data.plantId,
          createdBy: data.createdBy,
          updatedBy: data.createdBy,
        },
      })

      const version = await tx.workflowVersion.create({
        data: {
          workflowId: workflow.id,
          version: 1,
          status: 'draft',
          createdBy: data.createdBy,
          updatedBy: data.createdBy,
        },
      })

      const updated = await tx.workflow.update({
        where: { id: workflow.id },
        data: { currentVersionId: version.id },
      })

      const currentVersion: WorkflowVersionDetailModel = {
        ...(version as WorkflowVersionModel),
        phases: [],
      }

      return { ...(updated as WorkflowModel), currentVersion }
    }) as Promise<WorkflowDetailModel>
  }

  async update(
    id: string,
    data: {
      name?: string
      description?: string | null
      updatedBy: string
    },
  ): Promise<WorkflowModel> {
    return this.prisma.workflow.update({
      where: { id },
      data: {
        ...(data.name !== undefined ? { name: data.name } : {}),
        ...(data.description !== undefined ? { description: data.description } : {}),
        updatedBy: data.updatedBy,
        version: { increment: 1 },
      },
    }) as Promise<WorkflowModel>
  }

  async listVersions(workflowId: string): Promise<WorkflowVersionModel[]> {
    return this.prisma.workflowVersion.findMany({
      where: { workflowId },
      orderBy: { version: 'desc' },
    }) as Promise<WorkflowVersionModel[]>
  }

  async findVersionById(id: string): Promise<WorkflowVersionDetailModel | null> {
    const ver = await this.prisma.workflowVersion.findUnique({
      where: { id },
      include: {
        phases: {
          orderBy: { order: 'asc' },
          include: {
            groups: {
              orderBy: { order: 'asc' },
              include: {
                steps: { orderBy: { order: 'asc' } },
              },
            },
          },
        },
      },
    })

    return ver as WorkflowVersionDetailModel | null
  }

  async createVersion(
    workflowId: string,
    actorId: string,
  ): Promise<WorkflowVersionDetailModel> {
    return this.prisma.$transaction(async (tx) => {
      const workflow = await tx.workflow.findFirst({
        where: { id: workflowId, deletedAt: null },
      })

      if (!workflow) throw new Error(`Workflow ${workflowId} not found`)

      const latest = await tx.workflowVersion.findFirst({
        where: { workflowId },
        orderBy: { version: 'desc' },
      })

      const nextVersion = (latest?.version ?? 0) + 1

      // Clone phases/groups/steps from current version if it exists
      let phasesToClone: PhaseModel[] = []
      if (workflow.currentVersionId) {
        const current = await tx.workflowVersion.findUnique({
          where: { id: workflow.currentVersionId },
          include: {
            phases: {
              orderBy: { order: 'asc' },
              include: {
                groups: {
                  orderBy: { order: 'asc' },
                  include: { steps: { orderBy: { order: 'asc' } } },
                },
              },
            },
          },
        })
        phasesToClone = (current?.phases ?? []) as PhaseModel[]
      }

      const newVersion = await tx.workflowVersion.create({
        data: {
          workflowId,
          version: nextVersion,
          status: 'draft',
          createdBy: actorId,
          updatedBy: actorId,
        },
      })

      // Clone tree from previous version
      const clonedPhases: PhaseModel[] = []
      for (const phase of phasesToClone) {
        const newPhase = await tx.phase.create({
          data: {
            workflowVersionId: newVersion.id,
            order: phase.order,
            category: phase.category,
            name: phase.name,
            description: phase.description,
            isCycleBased: phase.isCycleBased,
            isAutoGenerated: phase.isAutoGenerated,
            createdBy: actorId,
            updatedBy: actorId,
          },
          include: { groups: { include: { steps: true } } },
        })

        const clonedGroups: GroupModel[] = []
        for (const group of phase.groups) {
          const newGroup = await tx.group.create({
            data: {
              phaseId: newPhase.id,
              order: group.order,
              category: group.category,
              name: group.name,
              description: group.description,
              supportsParallel: group.supportsParallel,
              supportsRecovery: group.supportsRecovery,
              isAutoGenerated: group.isAutoGenerated,
              createdBy: actorId,
              updatedBy: actorId,
            },
          })

          const clonedSteps: StepModel[] = []
          for (const step of group.steps) {
            const newStep = await tx.step.create({
              data: {
                groupId: newGroup.id,
                order: step.order,
                category: step.category,
                actionType: step.actionType,
                type: step.type,
                source: step.source,
                name: step.name,
                instructions: step.instructions,
                skillId: step.skillId,
                deviceId: step.deviceId,
                recipeId: step.recipeId,
                toolId: step.toolId,
                standardTimeSec: step.standardTimeSec,
                isRequired: step.isRequired,
                partReference: step.partReference,
                noTargetPolicy: step.noTargetPolicy,
                // PROMPT_7 D1 — propagate the polymorphic Step.data JSON
                // through clone so recoveryConfig + photoUrl + actionType
                // overrides survive workflow duplication.
                data: step.data,
                createdBy: actorId,
                updatedBy: actorId,
              },
            })
            clonedSteps.push(newStep as StepModel)
          }

          clonedGroups.push({ ...(newGroup as GroupModel), steps: clonedSteps })
        }

        clonedPhases.push({ ...(newPhase as PhaseModel), groups: clonedGroups })
      }

      // Update workflow's currentVersionId to the new version
      await tx.workflow.update({
        where: { id: workflowId },
        data: { currentVersionId: newVersion.id, updatedBy: actorId },
      })

      return { ...(newVersion as WorkflowVersionModel), phases: clonedPhases }
    }) as Promise<WorkflowVersionDetailModel>
  }

  async replaceVersionTree(
    versionId: string,
    phases: WorkflowPhaseInput[],
    actorId: string,
  ): Promise<WorkflowVersionDetailModel> {
    return this.prisma.$transaction(async (tx) => {
      // Cascade delete: deleting phases cascades to groups → steps
      await tx.phase.deleteMany({ where: { workflowVersionId: versionId } })

      const createdPhases: PhaseModel[] = []

      for (const phase of phases) {
        const newPhase = await tx.phase.create({
          data: {
            workflowVersionId: versionId,
            order: phase.order,
            category: phase.category,
            name: phase.name,
            description: phase.description ?? null,
            isCycleBased: phase.isCycleBased ?? false,
            isAutoGenerated: phase.isAutoGenerated ?? false,
            createdBy: actorId,
            updatedBy: actorId,
          },
        })

        const createdGroups: GroupModel[] = []
        for (const group of phase.groups) {
          const newGroup = await tx.group.create({
            data: {
              phaseId: newPhase.id,
              order: group.order,
              category: group.category,
              name: group.name,
              description: group.description ?? null,
              supportsParallel: group.supportsParallel ?? false,
              supportsRecovery: group.supportsRecovery ?? false,
              isAutoGenerated: group.isAutoGenerated ?? false,
              createdBy: actorId,
              updatedBy: actorId,
            },
          })

          const createdSteps: StepModel[] = []
          for (const step of group.steps) {
            // PROMPT_7 D1 — serialize polymorphic step.data to JSON string.
            // null means no extra payload; undefined collapses to null too.
            const serialisedData =
              step.data == null ? null : JSON.stringify(step.data)
            const newStep = await tx.step.create({
              data: {
                groupId: newGroup.id,
                order: step.order,
                category: step.category,
                actionType: step.actionType,
                type: step.type ?? 'normal',
                source: step.source ?? 'manual',
                name: step.name,
                instructions: step.instructions ?? null,
                skillId: step.skillId ?? null,
                deviceId: step.deviceId ?? null,
                recipeId: step.recipeId ?? null,
                toolId: step.toolId ?? null,
                standardTimeSec: step.standardTimeSec ?? null,
                isRequired: step.isRequired ?? true,
                partReference: step.partReference ?? null,
                noTargetPolicy: step.noTargetPolicy ?? null,
                data: serialisedData,
                createdBy: actorId,
                updatedBy: actorId,
              },
            })
            createdSteps.push(newStep as StepModel)
          }

          createdGroups.push({ ...(newGroup as GroupModel), steps: createdSteps })
        }

        createdPhases.push({ ...(newPhase as PhaseModel), groups: createdGroups })
      }

      const updatedVersion = await tx.workflowVersion.update({
        where: { id: versionId },
        data: { updatedBy: actorId },
      })

      return { ...(updatedVersion as WorkflowVersionModel), phases: createdPhases }
    }) as Promise<WorkflowVersionDetailModel>
  }

  async updateVersionNotes(
    versionId: string,
    notes: string,
    actorId: string,
  ): Promise<WorkflowVersionModel> {
    return this.prisma.workflowVersion.update({
      where: { id: versionId },
      data: { notes, updatedBy: actorId },
    }) as Promise<WorkflowVersionModel>
  }

  async approveVersion(
    versionId: string,
    actorId: string,
  ): Promise<WorkflowVersionModel> {
    return this.prisma.workflowVersion.update({
      where: { id: versionId },
      data: {
        status: 'approved',
        approvedBy: actorId,
        approvedAt: new Date(),
        updatedBy: actorId,
      },
    }) as Promise<WorkflowVersionModel>
  }

  async deprecateVersion(
    versionId: string,
    actorId: string,
    reason: string,
  ): Promise<WorkflowVersionModel> {
    const existing = await this.prisma.workflowVersion.findUnique({
      where: { id: versionId },
      select: { notes: true },
    })
    const reasonNote = `[DEPRECATED ${new Date().toISOString()}] ${reason}`
    const mergedNotes = existing?.notes ? `${existing.notes}\n${reasonNote}` : reasonNote

    return this.prisma.workflowVersion.update({
      where: { id: versionId },
      data: {
        status: 'deprecated',
        notes: mergedNotes,
        updatedBy: actorId,
      },
    }) as Promise<WorkflowVersionModel>
  }

  async cloneWorkflow(
    sourceWorkflowId: string,
    payload: { code: string; name: string; description: string | null; plantId: string },
    actorId: string,
  ): Promise<WorkflowDetailModel> {
    return this.prisma.$transaction(async (tx) => {
      const source = await tx.workflow.findFirst({
        where: { id: sourceWorkflowId, deletedAt: null },
      })
      if (!source) throw new Error(`Source workflow ${sourceWorkflowId} not found`)
      if (!source.currentVersionId) {
        throw new Error(`Source workflow ${sourceWorkflowId} has no current version to clone`)
      }

      const sourceTree = await tx.workflowVersion.findUnique({
        where: { id: source.currentVersionId },
        include: {
          phases: {
            orderBy: { order: 'asc' },
            include: {
              groups: {
                orderBy: { order: 'asc' },
                include: { steps: { orderBy: { order: 'asc' } } },
              },
            },
          },
        },
      })
      if (!sourceTree) {
        throw new Error(`Source workflow version ${source.currentVersionId} not found`)
      }

      const newWorkflow = await tx.workflow.create({
        data: {
          code: payload.code,
          name: payload.name,
          description: payload.description,
          itemId: source.itemId,
          plantId: payload.plantId,
          createdBy: actorId,
          updatedBy: actorId,
        },
      })

      const newVersion = await tx.workflowVersion.create({
        data: {
          workflowId: newWorkflow.id,
          version: 1,
          status: 'draft',
          createdBy: actorId,
          updatedBy: actorId,
        },
      })

      const clonedPhases: PhaseModel[] = []
      for (const phase of sourceTree.phases) {
        const newPhase = await tx.phase.create({
          data: {
            workflowVersionId: newVersion.id,
            order: phase.order,
            category: phase.category,
            name: phase.name,
            description: phase.description,
            isCycleBased: phase.isCycleBased,
            isAutoGenerated: phase.isAutoGenerated,
            createdBy: actorId,
            updatedBy: actorId,
          },
        })

        const clonedGroups: GroupModel[] = []
        for (const group of phase.groups) {
          const newGroup = await tx.group.create({
            data: {
              phaseId: newPhase.id,
              order: group.order,
              category: group.category,
              name: group.name,
              description: group.description,
              supportsParallel: group.supportsParallel,
              supportsRecovery: group.supportsRecovery,
              isAutoGenerated: group.isAutoGenerated,
              createdBy: actorId,
              updatedBy: actorId,
            },
          })

          const clonedSteps: StepModel[] = []
          for (const step of group.steps) {
            const newStep = await tx.step.create({
              data: {
                groupId: newGroup.id,
                order: step.order,
                category: step.category,
                actionType: step.actionType,
                type: step.type,
                source: step.source,
                name: step.name,
                instructions: step.instructions,
                skillId: step.skillId,
                deviceId: step.deviceId,
                recipeId: step.recipeId,
                toolId: step.toolId,
                standardTimeSec: step.standardTimeSec,
                isRequired: step.isRequired,
                partReference: step.partReference,
                noTargetPolicy: step.noTargetPolicy,
                // PROMPT_7 D1 — propagate the polymorphic Step.data JSON
                // through clone so recoveryConfig + photoUrl + actionType
                // overrides survive workflow duplication.
                data: step.data,
                createdBy: actorId,
                updatedBy: actorId,
              },
            })
            clonedSteps.push(newStep as StepModel)
          }

          clonedGroups.push({ ...(newGroup as GroupModel), steps: clonedSteps })
        }

        clonedPhases.push({ ...(newPhase as PhaseModel), groups: clonedGroups })
      }

      const updatedNew = await tx.workflow.update({
        where: { id: newWorkflow.id },
        data: { currentVersionId: newVersion.id },
      })

      const currentVersion: WorkflowVersionDetailModel = {
        ...(newVersion as WorkflowVersionModel),
        phases: clonedPhases,
      }

      return { ...(updatedNew as WorkflowModel), currentVersion }
    }) as Promise<WorkflowDetailModel>
  }
}
