/**
 * Workflow Snapshot deep-clone — D6 of PROMPT_5_FULL.
 *
 * When a Work Order is released, the source Workflow tree
 * (Phase → Group → Step) is deep-cloned into an immutable JSON payload
 * stored in `WorkflowSnapshot.snapshotData`. Per ADR-001 the snapshot is
 * NEVER mutated after creation: subsequent edits to the source workflow
 * produce a new version, but in-flight WOs continue to use their original
 * snapshot.
 *
 * The cloned shape preserves:
 *   - source IDs (so `StepExecution.stepId` can reference the original
 *     `Step` row — required by the existing step-execution machinery from
 *     D3/D5 that joins through `StepExecution.step`)
 *   - order across phases/groups/steps
 *   - all step semantics needed by HMI rendering: category, actionType,
 *     instructions, deviceCategory (parallel swimlane from D4),
 *     skillId/deviceId/recipeId/toolId references, isRequired
 *
 * The cloned shape strips:
 *   - Prisma `Date` instances (createdAt/updatedAt) → not load-bearing for
 *     execution
 *   - createdBy/updatedBy bookkeeping
 *
 * The output is a plain JSON-safe object that can be JSON.stringify-ed
 * directly into the SQLite TEXT column.
 */

export interface SourceStep {
  id: string
  groupId: string
  order: number
  category: string
  actionType: string
  type: string
  source: string
  name: string
  instructions: string | null
  skillId: string | null
  deviceId: string | null
  recipeId: string | null
  toolId: string | null
  standardTimeSec: number | null
  isRequired: boolean
  partReference: string | null
  noTargetPolicy: string | null
  deviceCategory: string | null
}

export interface SourceGroup {
  id: string
  phaseId: string
  order: number
  category: string
  name: string
  supportsParallel: boolean
  supportsRecovery: boolean
  isAutoGenerated: boolean
  description: string | null
  steps: SourceStep[]
}

export interface SourcePhase {
  id: string
  workflowVersionId: string
  order: number
  category: string
  name: string
  isCycleBased: boolean
  isAutoGenerated: boolean
  description: string | null
  groups: SourceGroup[]
}

export interface SourceWorkflowVersion {
  id: string
  workflowId: string
  version: number
  status: string
  notes: string | null
  phases: SourcePhase[]
}

export interface ClonedStep {
  id: string
  groupId: string
  order: number
  category: string
  actionType: string
  type: string
  source: string
  name: string
  instructions: string | null
  skillId: string | null
  deviceId: string | null
  recipeId: string | null
  toolId: string | null
  standardTimeSec: number | null
  isRequired: boolean
  partReference: string | null
  noTargetPolicy: string | null
  deviceCategory: string | null
}

export interface ClonedGroup {
  id: string
  phaseId: string
  order: number
  category: string
  name: string
  supportsParallel: boolean
  supportsRecovery: boolean
  isAutoGenerated: boolean
  description: string | null
  steps: ClonedStep[]
}

export interface ClonedPhase {
  id: string
  workflowVersionId: string
  order: number
  category: string
  name: string
  isCycleBased: boolean
  isAutoGenerated: boolean
  description: string | null
  groups: ClonedGroup[]
}

export interface WorkflowSnapshotPayload {
  schemaVersion: 1
  workflowId: string
  workflowVersionId: string
  workflowVersionNumber: number
  status: string
  notes: string | null
  phases: ClonedPhase[]
  clonedAt: string
}

/**
 * Clones a loaded Workflow tree into a plain, JSON-serializable payload
 * suitable for `WorkflowSnapshot.snapshotData`.
 *
 * The function is pure: it never mutates the input. Output preserves the
 * source ordering and IDs but strips bookkeeping fields. `clonedAt` lets
 * downstream consumers prove the snapshot was minted at release time
 * rather than reconstructed later.
 */
export function cloneWorkflowTree(
  source: SourceWorkflowVersion,
  clonedAt: Date = new Date(),
): WorkflowSnapshotPayload {
  const phases = source.phases
    .slice()
    .sort((a, b) => a.order - b.order)
    .map(clonePhase)
  return {
    schemaVersion: 1,
    workflowId: source.workflowId,
    workflowVersionId: source.id,
    workflowVersionNumber: source.version,
    status: source.status,
    notes: source.notes,
    phases,
    clonedAt: clonedAt.toISOString(),
  }
}

function clonePhase(phase: SourcePhase): ClonedPhase {
  return {
    id: phase.id,
    workflowVersionId: phase.workflowVersionId,
    order: phase.order,
    category: phase.category,
    name: phase.name,
    isCycleBased: phase.isCycleBased,
    isAutoGenerated: phase.isAutoGenerated,
    description: phase.description,
    groups: phase.groups
      .slice()
      .sort((a, b) => a.order - b.order)
      .map(cloneGroup),
  }
}

function cloneGroup(group: SourceGroup): ClonedGroup {
  return {
    id: group.id,
    phaseId: group.phaseId,
    order: group.order,
    category: group.category,
    name: group.name,
    supportsParallel: group.supportsParallel,
    supportsRecovery: group.supportsRecovery,
    isAutoGenerated: group.isAutoGenerated,
    description: group.description,
    steps: group.steps
      .slice()
      .sort((a, b) => a.order - b.order)
      .map(cloneStep),
  }
}

function cloneStep(step: SourceStep): ClonedStep {
  return {
    id: step.id,
    groupId: step.groupId,
    order: step.order,
    category: step.category,
    actionType: step.actionType,
    type: step.type,
    source: step.source,
    name: step.name,
    instructions: step.instructions,
    skillId: step.skillId,
    deviceId: step.deviceId,
    recipeId: step.recipeId,
    toolId: step.toolId,
    standardTimeSec: step.standardTimeSec,
    isRequired: step.isRequired,
    partReference: step.partReference,
    noTargetPolicy: step.noTargetPolicy,
    deviceCategory: step.deviceCategory,
  }
}

/**
 * Returns the flat list of source step IDs in workflow execution order.
 * Used by the release service to seed `StepExecution` rows in one
 * `createMany` call.
 */
export function listClonedStepIds(payload: WorkflowSnapshotPayload): string[] {
  const out: string[] = []
  for (const phase of payload.phases) {
    for (const group of phase.groups) {
      for (const step of group.steps) {
        out.push(step.id)
      }
    }
  }
  return out
}
