import { describe, it, expect } from 'vitest'
import {
  cloneWorkflowTree,
  listClonedStepIds,
  type SourceWorkflowVersion,
} from './workflow-snapshot.rules'

function makeStep(
  id: string,
  groupId: string,
  order: number,
  overrides: Partial<{
    category: string
    actionType: string
    deviceCategory: string | null
    isRequired: boolean
  }> = {},
) {
  return {
    id,
    groupId,
    order,
    category: overrides.category ?? 'production',
    actionType: overrides.actionType ?? 'NORMAL',
    type: 'normal',
    source: 'manual',
    name: `Step ${id}`,
    instructions: null,
    skillId: null,
    deviceId: null,
    recipeId: null,
    toolId: null,
    standardTimeSec: 60,
    isRequired: overrides.isRequired ?? true,
    partReference: null,
    noTargetPolicy: null,
    deviceCategory: overrides.deviceCategory ?? null,
  }
}

function makeWorkflow(): SourceWorkflowVersion {
  return {
    id: 'wfv-1',
    workflowId: 'wf-1',
    version: 3,
    status: 'approved',
    notes: 'Approved by QC',
    phases: [
      {
        id: 'phase-2',
        workflowVersionId: 'wfv-1',
        order: 2, // intentionally out-of-order — clone must sort
        category: 'production',
        name: 'Production',
        isCycleBased: true,
        isAutoGenerated: false,
        description: null,
        imageUrl: 'data:image/png;base64,PRODimg',
        groups: [
          {
            id: 'group-2-1',
            phaseId: 'phase-2',
            order: 1,
            category: 'device_execution',
            name: 'Extrusion',
            supportsParallel: true,
            supportsRecovery: true,
            isAutoGenerated: false,
            description: null,
            steps: [
              makeStep('step-c', 'group-2-1', 3, { deviceCategory: 'post' }),
              makeStep('step-a', 'group-2-1', 1, {
                deviceCategory: 'device_main',
              }),
              makeStep('step-b', 'group-2-1', 2, {
                deviceCategory: 'parallel',
              }),
            ],
          },
        ],
      },
      {
        id: 'phase-1',
        workflowVersionId: 'wfv-1',
        order: 1,
        category: 'inbound',
        name: 'Inbound',
        isCycleBased: false,
        isAutoGenerated: false,
        description: 'Material check',
        imageUrl: null,
        groups: [
          {
            id: 'group-1-1',
            phaseId: 'phase-1',
            order: 1,
            category: 'bom_check',
            name: 'BOM',
            supportsParallel: false,
            supportsRecovery: false,
            isAutoGenerated: false,
            description: null,
            steps: [
              makeStep('step-i', 'group-1-1', 1, { category: 'identification' }),
            ],
          },
        ],
      },
    ],
  }
}

describe('cloneWorkflowTree', () => {
  it('preserves IDs, version, status, and notes', () => {
    const cloned = cloneWorkflowTree(makeWorkflow())
    expect(cloned.workflowId).toBe('wf-1')
    expect(cloned.workflowVersionId).toBe('wfv-1')
    expect(cloned.workflowVersionNumber).toBe(3)
    expect(cloned.status).toBe('approved')
    expect(cloned.notes).toBe('Approved by QC')
    expect(cloned.schemaVersion).toBe(1)
  })

  it('sorts phases, groups, and steps by order ascending', () => {
    const cloned = cloneWorkflowTree(makeWorkflow())
    expect(cloned.phases.map((p) => p.id)).toEqual(['phase-1', 'phase-2'])
    const productionPhase = cloned.phases[1]
    if (!productionPhase) throw new Error('expected phase-2 in clone output')
    const productionGroup = productionPhase.groups[0]
    if (!productionGroup) throw new Error('expected group in phase-2')
    expect(productionGroup.steps.map((s) => s.id)).toEqual([
      'step-a',
      'step-b',
      'step-c',
    ])
  })

  it('preserves imageUrl on each phase (Fix-2 contract)', () => {
    const cloned = cloneWorkflowTree(makeWorkflow())
    expect(cloned.phases[0]?.imageUrl).toBeNull()
    expect(cloned.phases[1]?.imageUrl).toBe('data:image/png;base64,PRODimg')
  })

  it('preserves deviceCategory on parallel swimlane steps (D4 contract)', () => {
    const cloned = cloneWorkflowTree(makeWorkflow())
    const productionPhase = cloned.phases[1]
    if (!productionPhase) throw new Error('expected phase-2 in clone output')
    const productionGroup = productionPhase.groups[0]
    if (!productionGroup) throw new Error('expected group in phase-2')
    const [first, second, third] = productionGroup.steps
    expect(first?.deviceCategory).toBe('device_main')
    expect(second?.deviceCategory).toBe('parallel')
    expect(third?.deviceCategory).toBe('post')
  })

  it('does not mutate the source object', () => {
    const source = makeWorkflow()
    const before = JSON.stringify(source)
    cloneWorkflowTree(source)
    expect(JSON.stringify(source)).toBe(before)
  })

  it('round-trips through JSON without loss', () => {
    const cloned = cloneWorkflowTree(makeWorkflow())
    const roundtripped = JSON.parse(JSON.stringify(cloned))
    expect(roundtripped).toEqual(cloned)
  })

  it('handles empty workflow (no phases)', () => {
    const empty: SourceWorkflowVersion = {
      id: 'wfv-empty',
      workflowId: 'wf-empty',
      version: 1,
      status: 'approved',
      notes: null,
      phases: [],
    }
    const cloned = cloneWorkflowTree(empty)
    expect(cloned.phases).toEqual([])
  })

  it('uses provided clonedAt timestamp', () => {
    const fixed = new Date('2026-05-01T18:00:00.000Z')
    const cloned = cloneWorkflowTree(makeWorkflow(), fixed)
    expect(cloned.clonedAt).toBe(fixed.toISOString())
  })
})

describe('listClonedStepIds', () => {
  it('returns step IDs in execution order across phases and groups', () => {
    const payload = cloneWorkflowTree(makeWorkflow())
    expect(listClonedStepIds(payload)).toEqual([
      'step-i',
      'step-a',
      'step-b',
      'step-c',
    ])
  })

  it('returns [] for empty snapshot', () => {
    const payload = cloneWorkflowTree({
      id: 'x',
      workflowId: 'y',
      version: 1,
      status: 'approved',
      notes: null,
      phases: [],
    })
    expect(listClonedStepIds(payload)).toEqual([])
  })
})
