import { Handle, Position } from '@xyflow/react'
import type { NodeProps, Node } from '@xyflow/react'

export type StepNodeData = {
  label: string
  category: string
  source: string
  standardTimeSec: number | null
  order: number
  parentId?: string
}

export type StepNodeType = Node<StepNodeData, 'stepNode'>

function LockIcon() {
  return (
    <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-label="Auto-generato">
      <rect x="3" y="11" width="18" height="11" rx="2" ry="2" />
      <path d="M7 11V7a5 5 0 0 1 10 0v4" />
    </svg>
  )
}

export function StepNode({ data }: NodeProps<StepNodeType>) {
  const isAutoGenerated = data.source === 'auto_generated'

  return (
    <div className="rounded border border-neutral-200 bg-white px-3 py-2 min-w-[160px] shadow-sm text-left">
      <Handle type="target" position={Position.Top} />
      <div className="flex items-center justify-between mb-0.5">
        <span className="text-[10px] font-semibold uppercase tracking-wide text-neutral-400">
          Step {data.order}
        </span>
        {isAutoGenerated && (
          <span className="text-neutral-400" title="Auto-generato">
            <LockIcon />
          </span>
        )}
      </div>
      <div className="text-sm font-medium text-neutral-700">{data.label}</div>
      <div className="flex items-center gap-2 mt-0.5">
        <span className="text-[10px] text-neutral-400">{data.category.replace(/_/g, ' ')}</span>
        {data.standardTimeSec != null && (
          <span className="text-[10px] text-neutral-300">· {data.standardTimeSec}s</span>
        )}
      </div>
      <Handle type="source" position={Position.Bottom} />
    </div>
  )
}
