import { Handle, Position } from '@xyflow/react'
import type { NodeProps, Node } from '@xyflow/react'
import {
  ScanLine,
  Cog,
  ClipboardCheck,
  Truck,
  Wrench,
  Info,
  GitBranch,
  RotateCw,
  Hammer,
  type LucideIcon,
} from 'lucide-react'
import { NodeErrorBadge } from './NodeErrorBadge'

export type StepNodeData = {
  label: string
  category: string
  source: string
  standardTimeSec: number | null
  order: number
  parentId?: string
}

export type StepNodeType = Node<StepNodeData, 'stepNode'>

const STEP_CATEGORY_ICONS: Record<string, LucideIcon> = {
  identification: ScanLine,
  production: Cog,
  quality_control: ClipboardCheck,
  logistics: Truck,
  setup: Wrench,
  teardown: Hammer,
  decision: GitBranch,
  information: Info,
  recovery: RotateCw,
}

function LockIcon() {
  return (
    <svg
      width="10"
      height="10"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-label="Auto-generato"
    >
      <rect x="3" y="11" width="18" height="11" rx="2" ry="2" />
      <path d="M7 11V7a5 5 0 0 1 10 0v4" />
    </svg>
  )
}

export function StepNode({ id, data }: NodeProps<StepNodeType>) {
  const isAutoGenerated = data.source === 'auto_generated'
  const Icon = STEP_CATEGORY_ICONS[data.category] ?? ScanLine
  const stepCode = String(data.order).padStart(2, '0')

  return (
    <div
      className="rounded border border-neutral-200 bg-white shadow-sm text-left"
      style={{ width: 240 }}
      data-node-kind="step"
    >
      <Handle type="target" position={Position.Top} />
      <div className="flex items-center gap-2 px-2.5 py-1.5">
        <span className="font-mono text-[11px] font-semibold text-neutral-500 tabular-nums">
          {stepCode}
        </span>
        <Icon size={12} className="shrink-0 text-neutral-500" aria-hidden />
        <div className="min-w-0 flex-1">
          <div className="text-sm font-medium text-neutral-800 truncate">{data.label}</div>
          <div className="flex items-center gap-1.5 text-[10px] text-neutral-500">
            <span className="truncate">{data.category.replace(/_/g, ' ')}</span>
            {data.standardTimeSec != null && (
              <>
                <span aria-hidden>·</span>
                <span className="font-mono tabular-nums">{data.standardTimeSec}s</span>
              </>
            )}
          </div>
        </div>
        <span className="flex items-center gap-1 shrink-0">
          <NodeErrorBadge nodeId={id} />
          {isAutoGenerated && (
            <span className="text-neutral-400" title="Auto-generato">
              <LockIcon />
            </span>
          )}
        </span>
      </div>
      <Handle type="source" position={Position.Bottom} />
    </div>
  )
}
