import { z } from 'zod'

export const CreateWorkflowSchema = z.object({
  code: z.string().min(1).max(50),
  name: z.string().min(1).max(200),
  description: z.string().max(2000).optional(),
  itemId: z.string().cuid().optional(),
  plantId: z.string().cuid(),
})

export const UpdateWorkflowSchema = z
  .object({
    name: z.string().min(1).max(200),
    description: z.string().max(2000).nullable(),
  })
  .partial()

// ── Step input (leaf of the tree) ────────────────────────────────────────────

export const WorkflowStepInputSchema = z.object({
  order: z.number().int().min(1),
  category: z.string().min(1),
  actionType: z.string().min(1),
  type: z.string().default('normal'),
  source: z.string().default('manual'),
  name: z.string().min(1).max(200),
  instructions: z.string().optional(),
  skillId: z.string().cuid().optional(),
  deviceId: z.string().cuid().optional(),
  recipeId: z.string().cuid().optional(),
  toolId: z.string().cuid().optional(),
  standardTimeSec: z.number().int().positive().optional(),
  isRequired: z.boolean().default(true),
  partReference: z.string().optional(),
  noTargetPolicy: z.string().optional(),
})

export const WorkflowGroupInputSchema = z.object({
  order: z.number().int().min(1),
  category: z.string().min(1),
  name: z.string().min(1).max(200),
  description: z.string().optional(),
  supportsParallel: z.boolean().default(false),
  supportsRecovery: z.boolean().default(false),
  isAutoGenerated: z.boolean().default(false),
  steps: z.array(WorkflowStepInputSchema),
})

export const WorkflowPhaseInputSchema = z.object({
  order: z.number().int().min(1),
  category: z.string().min(1),
  name: z.string().min(1).max(200),
  description: z.string().optional(),
  isCycleBased: z.boolean().default(false),
  isAutoGenerated: z.boolean().default(false),
  groups: z.array(WorkflowGroupInputSchema),
})

export const UpdateWorkflowVersionSchema = z
  .object({
    notes: z.string().max(2000),
    phases: z.array(WorkflowPhaseInputSchema),
  })
  .partial()

// ── Derived types ─────────────────────────────────────────────────────────────

export type CreateWorkflowDto = z.infer<typeof CreateWorkflowSchema>
export type UpdateWorkflowDto = z.infer<typeof UpdateWorkflowSchema>
export type UpdateWorkflowVersionDto = z.infer<typeof UpdateWorkflowVersionSchema>
export type WorkflowPhaseInput = z.infer<typeof WorkflowPhaseInputSchema>
export type WorkflowGroupInput = z.infer<typeof WorkflowGroupInputSchema>
export type WorkflowStepInput = z.infer<typeof WorkflowStepInputSchema>
