import { z } from 'zod'

export const CreateWorkflowSchema = z.object({
  code: z.string().min(1).max(50),
  name: z.string().min(1).max(200),
  description: z.string().max(2000).optional(),
  itemId: z.string().cuid().optional(),
  plantId: z.string().cuid(),
})

export const UpdateWorkflowSchema = z
  .object({
    name: z.string().min(1).max(200),
    description: z.string().max(2000).nullable(),
  })
  .partial()

// ── Step input (leaf of the tree) ────────────────────────────────────────────

// PROMPT_7 D1 — recoveryConfig persistence on Step.data JSON.
// Mirrors apps/web/src/lib/step-validation-schemas.ts RecoveryConfigSchema —
// kept in sync by hand (the web copy is the authoring form, this is the
// transport contract sent on save). Step IDs may not be cuid() yet on first
// save (see WorkflowCanvas drop handler — uses `new-${Date.now()}` placeholders
// until the server reissues IDs), so preRetryStepIds is loose-typed.
export const StepRecoveryConfigSchema = z.object({
  enabled: z.boolean().default(false),
  maxAttempts: z.number().int().min(0).max(5).default(2),
  preRetryStepIds: z.array(z.string()).default([]),
})

// Polymorphic Step.data carrier. session-only fields exposed by the
// configurator (recoveryConfig + photoUrl + actionType) are persisted under
// this object so the workflow editor save/load roundtrip survives.
export const StepDataSchema = z
  .object({
    recoveryConfig: StepRecoveryConfigSchema.optional(),
    photoUrl: z.string().max(2000).optional(),
    actionType: z.string().max(100).optional(),
  })
  .passthrough()

export const WorkflowStepInputSchema = z.object({
  order: z.number().int().min(1),
  category: z.string().min(1),
  actionType: z.string().min(1),
  type: z.string().default('normal'),
  source: z.string().default('manual'),
  name: z.string().min(1).max(200),
  instructions: z.string().optional(),
  skillId: z.string().cuid().optional(),
  deviceId: z.string().cuid().optional(),
  recipeId: z.string().cuid().optional(),
  toolId: z.string().cuid().optional(),
  standardTimeSec: z.number().int().positive().optional(),
  isRequired: z.boolean().default(true),
  partReference: z.string().optional(),
  noTargetPolicy: z.string().optional(),
  /** PROMPT_7 D1 — polymorphic JSON; nullable on save (omits → no-op). */
  data: StepDataSchema.nullable().optional(),
})

export const WorkflowGroupInputSchema = z.object({
  order: z.number().int().min(1),
  category: z.string().min(1),
  name: z.string().min(1).max(200),
  description: z.string().optional(),
  supportsParallel: z.boolean().default(false),
  supportsRecovery: z.boolean().default(false),
  isAutoGenerated: z.boolean().default(false),
  steps: z.array(WorkflowStepInputSchema),
})

export const WorkflowPhaseInputSchema = z.object({
  order: z.number().int().min(1),
  category: z.string().min(1),
  name: z.string().min(1).max(200),
  description: z.string().optional(),
  isCycleBased: z.boolean().default(false),
  isAutoGenerated: z.boolean().default(false),
  groups: z.array(WorkflowGroupInputSchema),
})

export const UpdateWorkflowVersionSchema = z
  .object({
    notes: z.string().max(2000),
    phases: z.array(WorkflowPhaseInputSchema),
  })
  .partial()

// ── Versioning lifecycle (PROMPT_3b Session B) ───────────────────────────────

export const DeprecateWorkflowVersionSchema = z.object({
  reason: z
    .string()
    .min(10, 'La motivazione deve contenere almeno 10 caratteri')
    .max(2000),
})

// ── Templates wizard (PROMPT_3b Session B) ───────────────────────────────────

export const CloneWorkflowSchema = z.object({
  code: z.string().min(1).max(50),
  name: z.string().min(1).max(200),
  description: z.string().max(2000).optional(),
  plantId: z.string().cuid().optional(),
})

// ── Derived types ─────────────────────────────────────────────────────────────

export type CreateWorkflowDto = z.infer<typeof CreateWorkflowSchema>
export type UpdateWorkflowDto = z.infer<typeof UpdateWorkflowSchema>
export type UpdateWorkflowVersionDto = z.infer<typeof UpdateWorkflowVersionSchema>
export type DeprecateWorkflowVersionDto = z.infer<typeof DeprecateWorkflowVersionSchema>
export type CloneWorkflowDto = z.infer<typeof CloneWorkflowSchema>
export type WorkflowPhaseInput = z.infer<typeof WorkflowPhaseInputSchema>
export type WorkflowGroupInput = z.infer<typeof WorkflowGroupInputSchema>
export type WorkflowStepInput = z.infer<typeof WorkflowStepInputSchema>
export type StepData = z.infer<typeof StepDataSchema>
export type StepRecoveryConfig = z.infer<typeof StepRecoveryConfigSchema>
