import { describe, it, expect } from 'vitest'
import { cloneWorkflowTree, type SourceWorkflowVersion } from '@mes/domain'
import { PNE_WORKFLOW_V1, PNE_WORKFLOW_V1_COUNTS } from '../workflow-v1'

// Pure-shape test: build a SourceWorkflowVersion from the static workflow
// definitions (without DB) and verify cloneWorkflowTree produces a payload
// matching expected counts. This protects the WO-release snapshot path
// without requiring DB integration.
describe('PNE workflow v1 → snapshot payload via cloneWorkflowTree', () => {
  it('produces a payload with 4 phases / 6 groups / 34 steps preserving order', () => {
    // Build a synthetic SourceWorkflowVersion from PNE_WORKFLOW_V1
    const source: SourceWorkflowVersion = {
      id: 'wfv-test',
      workflowId: 'wf-test',
      version: 1,
      status: 'approved',
      notes: null,
      phases: PNE_WORKFLOW_V1.phases.map((p, pi) => ({
        id: `phase-${pi}`,
        workflowVersionId: 'wfv-test',
        order: p.order,
        category: p.category,
        name: p.name,
        isCycleBased: p.isCycleBased,
        isAutoGenerated: false,
        description: null,
        groups: p.groups.map((g, gi) => ({
          id: `group-${pi}-${gi}`,
          phaseId: `phase-${pi}`,
          order: g.order,
          category: g.category,
          name: g.name,
          supportsParallel: g.supportsParallel ?? false,
          supportsRecovery: g.supportsRecovery ?? false,
          isAutoGenerated: g.isAutoGenerated ?? false,
          description: g.description ?? null,
          steps: g.steps.map((s, si) => ({
            id: `step-${pi}-${gi}-${si}`,
            groupId: `group-${pi}-${gi}`,
            order: s.order,
            category: s.category,
            actionType: s.actionType,
            type: 'normal',
            source: 'manual',
            name: s.name,
            instructions: s.instructions ?? null,
            skillId: null,
            deviceId: null,
            recipeId: null,
            toolId: null,
            standardTimeSec: s.standardTimeSec ?? null,
            isRequired: s.isRequired ?? true,
            partReference: s.partReference ?? null,
            noTargetPolicy: null,
            deviceCategory: s.deviceCategory ?? null,
          })),
        })),
      })),
    }

    const fixed = new Date('2026-05-02T18:00:00Z')
    const payload = cloneWorkflowTree(source, fixed)

    expect(payload.schemaVersion).toBe(1)
    expect(payload.workflowVersionId).toBe('wfv-test')
    expect(payload.workflowVersionNumber).toBe(1)
    expect(payload.status).toBe('approved')
    expect(payload.clonedAt).toBe('2026-05-02T18:00:00.000Z')

    expect(payload.phases).toHaveLength(PNE_WORKFLOW_V1_COUNTS.phases)
    const totalGroups = payload.phases.reduce((s, p) => s + p.groups.length, 0)
    const totalSteps = payload.phases.reduce(
      (s, p) => s + p.groups.reduce((gs, g) => gs + g.steps.length, 0),
      0,
    )
    expect(totalGroups).toBe(PNE_WORKFLOW_V1_COUNTS.groups)
    expect(totalSteps).toBe(PNE_WORKFLOW_V1_COUNTS.steps)

    // Order preserved across the tree
    expect(payload.phases.map((p) => p.order)).toEqual([1, 2, 3, 4])
    for (const phase of payload.phases) {
      const groupOrders = phase.groups.map((g) => g.order)
      expect(groupOrders).toEqual([...groupOrders].sort((a, b) => a - b))
      for (const group of phase.groups) {
        const stepOrders = group.steps.map((s) => s.order)
        expect(stepOrders).toEqual([...stepOrders].sort((a, b) => a - b))
      }
    }

    // Snapshot payload is JSON-safe (no Date / undefined / function)
    const jsonString = JSON.stringify(payload)
    expect(jsonString.length).toBeGreaterThan(1000)
    const reparsed = JSON.parse(jsonString)
    expect(reparsed.phases).toHaveLength(4)
  })
})
