import { describe, it, expect } from 'vitest'
import { PNE_WORKFLOW_V1, PNE_WORKFLOW_V1_COUNTS, PNE_WORKFLOW_V1_CODE } from '../workflow-v1'

describe('PNE workflow v1 — structure', () => {
  it('has 4 phases / 6 groups / 34 step rows with correct categories per PROMPT § 3.2', () => {
    expect(PNE_WORKFLOW_V1_CODE).toBe('wf-pneumatic-air-680-v1')

    // Aggregate counts (PROMPT § 1 said "19 steps" — informal undercount;
    // enumeration is 26 main-path + 8 inline recovery = 34 step rows.
    // See TODO-042 doc-hygiene entry to be opened in D4.)
    expect(PNE_WORKFLOW_V1_COUNTS.phases).toBe(4)
    expect(PNE_WORKFLOW_V1_COUNTS.groups).toBe(6)
    expect(PNE_WORKFLOW_V1_COUNTS.steps).toBe(34)
    expect(PNE_WORKFLOW_V1_COUNTS.recoveryGroups).toBe(2) // B2 + C2 inline

    // Phase categories per PROMPT § 3.2
    const phaseCategories = PNE_WORKFLOW_V1.phases.map((p) => p.category)
    expect(phaseCategories).toEqual(['production', 'quality_control', 'quality_control', 'outbound'])

    // isCycleBased: P1/P2/P3 yes, P4 no (sub-loops by box capacity)
    const cycleFlags = PNE_WORKFLOW_V1.phases.map((p) => p.isCycleBased)
    expect(cycleFlags).toEqual([true, true, true, false])

    // Group counts per phase
    const groupsPerPhase = PNE_WORKFLOW_V1.phases.map((p) => p.groups.length)
    expect(groupsPerPhase).toEqual([1, 2, 2, 1])

    // Step counts per group (8 + 9 + 4 + 4 + 4 + 5)
    const stepCounts: number[] = []
    for (const p of PNE_WORKFLOW_V1.phases) for (const g of p.groups) stepCounts.push(g.steps.length)
    expect(stepCounts).toEqual([8, 9, 4, 4, 4, 5])

    // Step categories use only the StepCategory enum vocabulary
    const validStepCategories = ['production', 'logistics', 'identification', 'quality_control', 'decision', 'information', 'setup', 'teardown']
    for (const p of PNE_WORKFLOW_V1.phases) {
      for (const g of p.groups) {
        for (const s of g.steps) {
          expect(validStepCategories).toContain(s.category)
        }
      }
    }
  })

  it('Phase 4 packaging group has isAutoGenerated=true (AUTO-GEN tag per PROMPT § 3.2)', () => {
    const phase4 = PNE_WORKFLOW_V1.phases[3]!
    expect(phase4.category).toBe('outbound')
    const group = phase4.groups[0]!
    expect(group.isAutoGenerated).toBe(true)
  })
})
