// PROMPT_PNE_2 D3 — WorkflowSnapshot creation helper.
//
// Loads the full Workflow tree (Phase → Group → Step) for the given
// WorkflowVersion, calls cloneWorkflowTree from @mes/domain to produce the
// JSON-safe payload, then writes the WorkflowSnapshot row.
//
// Idempotent: WorkflowSnapshot.workOrderId is @unique → if a snapshot exists
// for the WO, this is a no-op (per ADR-001 the snapshot is immutable post-
// release; re-running the seed must not mutate it).
//
// Mirrors the baseline release.service pattern but bypasses the service
// (release service requires API request context unavailable in a seed).

import { cloneWorkflowTree, type SourceWorkflowVersion } from '@mes/domain'
import { SYSTEM, type Prisma } from './upsert'

export async function createSnapshot(
  prisma: Prisma,
  workflowVersionId: string,
  workOrderId: string,
  releasedAt: Date,
): Promise<{ snapshotId: string; stepIds: string[] }> {
  // Skip if the WO already has a snapshot (immutable per ADR-001).
  const existing = await prisma.workflowSnapshot.findUnique({ where: { workOrderId } })
  if (existing) {
    const phases = await prisma.phase.findMany({
      where: { workflowVersionId },
      orderBy: { order: 'asc' },
      include: { groups: { include: { steps: { orderBy: { order: 'asc' } } }, orderBy: { order: 'asc' } } },
    })
    const stepIds: string[] = []
    for (const p of phases) for (const g of p.groups) for (const s of g.steps) stepIds.push(s.id)
    return { snapshotId: existing.id, stepIds }
  }

  const wfWithTree = await prisma.workflowVersion.findUniqueOrThrow({
    where: { id: workflowVersionId },
    include: {
      phases: {
        orderBy: { order: 'asc' },
        include: {
          groups: {
            orderBy: { order: 'asc' },
            include: { steps: { orderBy: { order: 'asc' } } },
          },
        },
      },
    },
  })

  // Adapt Prisma rows → SourceWorkflowVersion (strip Date / bookkeeping fields).
  const source: SourceWorkflowVersion = {
    id: wfWithTree.id,
    workflowId: wfWithTree.workflowId,
    version: wfWithTree.version,
    status: wfWithTree.status,
    notes: wfWithTree.notes,
    phases: wfWithTree.phases.map((p) => ({
      id: p.id,
      workflowVersionId: p.workflowVersionId,
      order: p.order,
      category: p.category,
      name: p.name,
      isCycleBased: p.isCycleBased,
      isAutoGenerated: p.isAutoGenerated,
      description: p.description,
      groups: p.groups.map((g) => ({
        id: g.id,
        phaseId: g.phaseId,
        order: g.order,
        category: g.category,
        name: g.name,
        supportsParallel: g.supportsParallel,
        supportsRecovery: g.supportsRecovery,
        isAutoGenerated: g.isAutoGenerated,
        description: g.description,
        steps: g.steps.map((s) => ({
          id: s.id,
          groupId: s.groupId,
          order: s.order,
          category: s.category,
          actionType: s.actionType,
          type: s.type,
          source: s.source,
          name: s.name,
          instructions: s.instructions,
          skillId: s.skillId,
          deviceId: s.deviceId,
          recipeId: s.recipeId,
          toolId: s.toolId,
          standardTimeSec: s.standardTimeSec,
          isRequired: s.isRequired,
          partReference: s.partReference,
          noTargetPolicy: s.noTargetPolicy,
          deviceCategory: s.deviceCategory,
        })),
      })),
    })),
  }

  const payload = cloneWorkflowTree(source, releasedAt)
  const snapshot = await prisma.workflowSnapshot.create({
    data: {
      workflowVersionId,
      workOrderId,
      snapshotData: JSON.stringify(payload),
      createdBy: SYSTEM,
    },
  })

  const stepIds: string[] = []
  for (const p of source.phases) for (const g of p.groups) for (const s of g.steps) stepIds.push(s.id)
  return { snapshotId: snapshot.id, stepIds }
}
