// PROMPT_7 D1 — pure helpers used by `WorkflowCanvas` to (de)serialise step
// payloads against the API. Extracted so they can be unit-tested without the
// React Flow runtime.

import type { Node } from '@xyflow/react'

export interface ParsedStepData {
  recoveryConfig?: unknown
  photoUrl?: string
  actionType?: string
  [k: string]: unknown
}

/**
 * Defensive parse of `Step.data`. Returns `null` when the JSON is missing or
 * malformed — never throws, since a corrupted blob shouldn't brick the canvas.
 */
export function parseStepData(raw: string | null | undefined): ParsedStepData | null {
  if (!raw) return null
  try {
    const obj: unknown = JSON.parse(raw)
    if (obj && typeof obj === 'object' && !Array.isArray(obj)) {
      return obj as ParsedStepData
    }
    return null
  } catch {
    return null
  }
}

const DEFAULT_ACTION_TYPE: Record<string, string> = {
  production: 'assembly',
  logistics: 'move',
  identification: 'scan_qr',
  quality_control: 'visual_check',
  decision: 'manual_choice',
  information: 'read_sop',
  setup: 'verify_workstation',
  teardown: 'cleanup',
  recovery: 'rework',
}

interface BuiltStep {
  order: number
  category: string
  actionType: string
  type: string
  source: string
  name: string
  instructions?: string
  skillId?: string
  deviceId?: string
  recipeId?: string
  toolId?: string
  workUnitId?: string
  standardTimeSec?: number
  isRequired: boolean
  data?: Record<string, unknown>
}

interface BuiltGroup {
  order: number
  category: string
  name: string
  supportsParallel: boolean
  supportsRecovery: boolean
  isAutoGenerated: boolean
  steps: BuiltStep[]
}

interface BuiltPhase {
  order: number
  category: string
  name: string
  isCycleBased: boolean
  isAutoGenerated: boolean
  imageUrl?: string | null
  groups: BuiltGroup[]
}

/**
 * Map React Flow nodes into the API's nested phases→groups→steps payload.
 *
 * PROMPT_7 D1: also persists session-only configurator fields (recoveryConfig,
 * photoUrl, actionType) under each step's polymorphic `data` slot, resolving
 * recoveryConfig from either the top-level `node.data.recoveryConfig`
 * (loaded from server) OR the nested `node.data.actionConfig.automatic.recoveryConfig`
 * (path used by AddStepDialog at create time).
 */
export function buildSavePayload(nodes: Node[]): BuiltPhase[] {
  const phaseNodes = nodes.filter((n) => n.type === 'phaseNode')
  return phaseNodes.map((phase) => ({
    order: phase.data['order'] as number,
    category: phase.data['category'] as string,
    name: phase.data['label'] as string,
    isCycleBased:
      typeof phase.data['isCycleBased'] === 'boolean'
        ? (phase.data['isCycleBased'] as boolean)
        : false,
    isAutoGenerated: false,
    imageUrl:
      typeof phase.data['imageUrl'] === 'string' && (phase.data['imageUrl'] as string).length > 0
        ? (phase.data['imageUrl'] as string)
        : null,
    groups: nodes
      .filter((n) => n.type === 'groupNode' && n.data['parentId'] === phase.id)
      .map((group) => ({
        order: group.data['order'] as number,
        category: group.data['category'] as string,
        name: group.data['label'] as string,
        supportsParallel:
          typeof group.data['supportsParallel'] === 'boolean'
            ? (group.data['supportsParallel'] as boolean)
            : false,
        supportsRecovery:
          typeof group.data['supportsRecovery'] === 'boolean'
            ? (group.data['supportsRecovery'] as boolean)
            : false,
        isAutoGenerated: false,
        steps: nodes
          .filter((n) => n.type === 'stepNode' && n.data['parentId'] === group.id)
          .map((step): BuiltStep => {
            const category = step.data['category'] as string
            const actionType =
              (step.data['actionType'] as string | undefined) ||
              DEFAULT_ACTION_TYPE[category] ||
              'assembly'
            const instructions = step.data['instructions'] as string | undefined
            const skillId = step.data['skillId'] as string | undefined
            const deviceId = step.data['deviceId'] as string | undefined
            const recipeId = step.data['recipeId'] as string | undefined
            const toolId = step.data['toolId'] as string | undefined
            const workUnitId = step.data['workUnitId'] as string | undefined
            const standardTimeSec =
              typeof step.data['standardTimeSec'] === 'number'
                ? (step.data['standardTimeSec'] as number)
                : typeof step.data['durationSec'] === 'number'
                  ? (step.data['durationSec'] as number)
                  : null
            const isRequired =
              typeof step.data['isRequired'] === 'boolean'
                ? (step.data['isRequired'] as boolean)
                : true
            // Resolve recoveryConfig + photoUrl from either top-level
            // node.data slots or the AddStepDialog's nested actionConfig blob.
            const topLevelRecovery = step.data['recoveryConfig']
            const actionConfigBlob = step.data['actionConfig'] as
              | { automatic?: { recoveryConfig?: unknown; photoUrl?: string } }
              | undefined
            const nestedRecovery = actionConfigBlob?.automatic?.recoveryConfig
            const recoveryConfig =
              topLevelRecovery && typeof topLevelRecovery === 'object'
                ? topLevelRecovery
                : nestedRecovery && typeof nestedRecovery === 'object'
                  ? nestedRecovery
                  : null
            const photoUrl =
              (step.data['photoUrl'] as string | undefined) ??
              actionConfigBlob?.automatic?.photoUrl
            const dataPayload: Record<string, unknown> = {}
            if (recoveryConfig) {
              dataPayload['recoveryConfig'] = recoveryConfig
            }
            if (typeof photoUrl === 'string' && photoUrl.length > 0) {
              dataPayload['photoUrl'] = photoUrl
            }
            if (typeof actionType === 'string' && actionType.length > 0) {
              dataPayload['actionType'] = actionType
            }
            const hasData =
              dataPayload['recoveryConfig'] !== undefined ||
              dataPayload['photoUrl'] !== undefined
            return {
              order: step.data['order'] as number,
              category,
              actionType,
              type: (step.data['type'] as string | undefined) ?? 'normal',
              source: (step.data['source'] as string | undefined) ?? 'manual',
              name: step.data['label'] as string,
              ...(instructions ? { instructions } : {}),
              ...(skillId ? { skillId } : {}),
              ...(deviceId ? { deviceId } : {}),
              ...(recipeId ? { recipeId } : {}),
              ...(toolId ? { toolId } : {}),
              ...(workUnitId ? { workUnitId } : {}),
              ...(typeof standardTimeSec === 'number' ? { standardTimeSec } : {}),
              isRequired,
              ...(hasData ? { data: dataPayload } : {}),
            }
          }),
      })),
  }))
}
