'use client'

// PROMPT_VIEWSWITCHER_WORKFLOWS — vertical card view of a workflow.
// Cards are grouped by phase: each phase gets a header card with accent color
// + counts, followed by one card per step (group name shown inline).
// Click on a step card drives `useWorkflowStore.selectNode(id, 'stepNode')`
// so Inspector + Live Preview stay in sync regardless of view mode.

import type { WorkflowModel, WorkflowStepModel } from '@mes/sdk'
import { Badge } from '@mes/ui'
import { useWorkflowStore } from './store'
import { phaseColor } from '../../lib/phase-color'

function formatDuration(seconds: number | null | undefined): string {
  if (seconds == null || seconds <= 0) return '—'
  if (seconds < 60) return `${seconds}s`
  const minutes = Math.floor(seconds / 60)
  const rem = seconds % 60
  if (minutes < 60) return rem === 0 ? `${minutes}m` : `${minutes}m ${rem}s`
  const hours = Math.floor(minutes / 60)
  const mRem = minutes % 60
  return mRem === 0 ? `${hours}h` : `${hours}h ${mRem}m`
}

interface StepCardProps {
  step: WorkflowStepModel
  groupName: string
  selected: boolean
  onSelect: () => void
}

function StepCard({ step, groupName, selected, onSelect }: StepCardProps) {
  return (
    <button
      type="button"
      onClick={onSelect}
      data-testid={`card-step-${step.id}`}
      data-selected={selected ? 'true' : 'false'}
      className={[
        'block w-full text-left rounded-md border p-3 transition-colors',
        selected
          ? 'border-accent bg-accent-soft text-accent-ink ring-1 ring-accent'
          : 'border-line bg-paper hover:bg-paper-2',
      ].join(' ')}
    >
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0">
          <div className="text-sm font-semibold truncate">{step.name}</div>
          <div className="text-[11px] text-ink-3 mt-0.5 truncate">{groupName}</div>
        </div>
        <Badge tone="neutral" className="!text-[10px] shrink-0">
          {step.actionType ?? step.category}
        </Badge>
      </div>
      <div className="mt-2 flex items-center gap-2 text-[11px] text-ink-3 tabular">
        <span>Durata: {formatDuration(step.standardTimeSec)}</span>
      </div>
    </button>
  )
}

export interface WorkflowCardViewProps {
  workflow: WorkflowModel
}

export function WorkflowCardView({ workflow }: WorkflowCardViewProps) {
  const phases = workflow.currentVersion?.phases ?? []
  const selectedNodeId = useWorkflowStore((s) => s.selectedNodeId)
  const selectNode = useWorkflowStore((s) => s.selectNode)

  if (phases.length === 0) {
    return (
      <div
        className="flex items-center justify-center h-full text-sm text-ink-3 px-6 text-center"
        data-testid="empty-state"
      >
        Nessuna fase nel workflow. Aggiungi una fase dalla palette per iniziare.
      </div>
    )
  }

  return (
    <div className="h-full overflow-auto p-3 space-y-4" data-testid="workflow-card-view">
      {phases.map((phase) => {
        const totalSteps = phase.groups.reduce((acc, g) => acc + g.steps.length, 0)
        const totalDuration = phase.groups.reduce(
          (acc, g) => acc + g.steps.reduce((s, st) => s + (st.standardTimeSec ?? 0), 0),
          0,
        )
        const accent = phaseColor(phase.category)
        return (
          <section key={`phase-${phase.id}`} data-testid={`phase-section-${phase.id}`}>
            <div
              className="rounded-md border border-line bg-paper px-3 py-2 mb-2"
              style={{ borderLeft: `3px solid ${accent}` }}
              data-testid={`phase-header-${phase.id}`}
            >
              <div className="flex items-center gap-2">
                <span className="font-semibold text-sm">{phase.name}</span>
                {phase.isAutoGenerated && (
                  <Badge tone="accent" className="!text-[10px]">
                    AUTO
                  </Badge>
                )}
                <span className="ml-auto font-mono text-[11px] text-ink-3">
                  {totalSteps} step · {formatDuration(totalDuration)}
                </span>
              </div>
            </div>

            <div className="grid grid-cols-1 gap-2 pl-3">
              {phase.groups.flatMap((group) =>
                group.steps.map((step) => (
                  <StepCard
                    key={`step-${step.id}`}
                    step={step}
                    groupName={group.name}
                    selected={selectedNodeId === step.id}
                    onSelect={() => selectNode(step.id, 'stepNode')}
                  />
                )),
              )}
              {totalSteps === 0 && (
                <div className="text-[11px] text-ink-3 italic px-2 py-1.5">
                  Nessuno step in questa fase.
                </div>
              )}
            </div>
          </section>
        )
      })}
    </div>
  )
}
