import { describe, it, expect, beforeEach, vi } from 'vitest'
import { render, screen, fireEvent } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import type { ReactNode } from 'react'
import type { WorkflowModel } from '@mes/sdk'

// PROMPT_15 C.5 — WorkflowHierarchyTable now fetches the equipment tree to
// hydrate the Postazione column. Tests mock the SDK to a flat empty tree so
// the table renders without external dependencies.
vi.mock('../../lib/sdk', () => ({
  sdk: {
    equipment: { tree: vi.fn().mockResolvedValue([]) },
  },
}))

import { WorkflowHierarchyTable } from './WorkflowHierarchyTable'
import { useWorkflowStore } from './store'

function renderWithQuery(node: ReactNode) {
  const client = new QueryClient({ defaultOptions: { queries: { retry: false, gcTime: 0 } } })
  return render(<QueryClientProvider client={client}>{node}</QueryClientProvider>)
}

function makeWorkflow(): WorkflowModel {
  const meta = {
    createdAt: '2026-05-01T00:00:00.000Z',
    updatedAt: '2026-05-01T00:00:00.000Z',
    createdBy: 'system',
    updatedBy: 'system',
  }
  return {
    id: 'wf-1',
    code: 'WF-TEST',
    name: 'Test Workflow',
    plantId: 'plant-1',
    version: 1,
    ...meta,
    currentVersion: {
      id: 'wfv-1',
      workflowId: 'wf-1',
      version: 1,
      status: 'draft',
      ...meta,
      phases: [
        {
          id: 'phase-1',
          workflowVersionId: 'wfv-1',
          order: 1,
          category: 'production',
          name: 'Estrusione',
          isCycleBased: true,
          isAutoGenerated: false,
          ...meta,
          groups: [
            {
              id: 'group-1',
              phaseId: 'phase-1',
              order: 1,
              category: 'cycle',
              name: 'Estrusione PA12',
              supportsParallel: false,
              supportsRecovery: false,
              isAutoGenerated: false,
              ...meta,
              steps: [
                {
                  id: 'step-1',
                  groupId: 'group-1',
                  order: 1,
                  category: 'production',
                  actionType: 'machine_run',
                  type: 'cycle',
                  source: 'manual',
                  name: 'Avvia estrusore',
                  isRequired: true,
                  standardTimeSec: 90,
                  ...meta,
                },
                {
                  id: 'step-2',
                  groupId: 'group-1',
                  order: 2,
                  category: 'quality_control',
                  actionType: 'visual_check',
                  type: 'cycle',
                  source: 'manual',
                  name: 'Controllo visivo',
                  isRequired: true,
                  standardTimeSec: 30,
                  ...meta,
                },
              ],
            },
          ],
        },
        {
          id: 'phase-2',
          workflowVersionId: 'wfv-1',
          order: 2,
          category: 'outbound',
          name: 'Spedizione',
          isCycleBased: false,
          isAutoGenerated: true,
          ...meta,
          groups: [],
        },
      ],
    },
  }
}

function resetStore() {
  useWorkflowStore.setState({
    nodes: [],
    edges: [],
    selectedNodeId: null,
    selectedNodeType: null,
    isDirty: false,
    history: { past: [], future: [] },
    dragSource: null,
    addStepDialog: {
      open: false,
      groupId: null,
      preselectedKind: null,
      preselectedCategory: null,
    },
    canvasSetNodes: null,
    triggerAutoSave: null,
    scrollToNode: null,
  })
}

describe('WorkflowHierarchyTable', () => {
  beforeEach(() => {
    resetStore()
  })

  it('renders all phases, groups and steps from the workflow', () => {
    renderWithQuery(<WorkflowHierarchyTable workflow={makeWorkflow()} />)
    // Phase rows
    expect(screen.getByText('Estrusione')).toBeInTheDocument()
    expect(screen.getByText('Spedizione')).toBeInTheDocument()
    // Group row
    expect(screen.getByText('Estrusione PA12')).toBeInTheDocument()
    // Step rows
    expect(screen.getByText('Avvia estrusore')).toBeInTheDocument()
    expect(screen.getByText('Controllo visivo')).toBeInTheDocument()
    // Auto-gen badge on phase 2
    expect(screen.getAllByText('AUTO').length).toBeGreaterThanOrEqual(1)
  })

  it('clicking a step row calls selectNode(stepId, "stepNode")', () => {
    renderWithQuery(<WorkflowHierarchyTable workflow={makeWorkflow()} />)
    fireEvent.click(screen.getByTestId('row-stepNode-step-1'))
    const state = useWorkflowStore.getState()
    expect(state.selectedNodeId).toBe('step-1')
    expect(state.selectedNodeType).toBe('stepNode')
  })

  it('toggling a phase chevron collapses its descendant rows', () => {
    renderWithQuery(<WorkflowHierarchyTable workflow={makeWorkflow()} />)
    expect(screen.getByText('Estrusione PA12')).toBeInTheDocument()
    fireEvent.click(screen.getByTestId('chevron-phase-1'))
    expect(screen.queryByText('Estrusione PA12')).toBeNull()
    expect(screen.queryByText('Avvia estrusore')).toBeNull()
    fireEvent.click(screen.getByTestId('chevron-phase-1'))
    expect(screen.getByText('Estrusione PA12')).toBeInTheDocument()
  })

  it('selected row gets accent-soft styling when selectedNodeId matches', () => {
    useWorkflowStore.setState({ selectedNodeId: 'step-1', selectedNodeType: 'stepNode' })
    renderWithQuery(<WorkflowHierarchyTable workflow={makeWorkflow()} />)
    const row = screen.getByTestId('row-stepNode-step-1')
    expect(row).toHaveAttribute('data-selected', 'true')
    expect(row.className).toMatch(/bg-accent-soft/)
  })

  it('renders the empty-state copy when the workflow has no phases', () => {
    const empty: WorkflowModel = {
      ...makeWorkflow(),
      currentVersion: { ...makeWorkflow().currentVersion!, phases: [] },
    }
    renderWithQuery(<WorkflowHierarchyTable workflow={empty} />)
    expect(screen.getByTestId('empty-state').textContent).toMatch(
      /Nessuna fase nel workflow/,
    )
  })

  it('readOnly mode does not call selectNode on row click', () => {
    renderWithQuery(<WorkflowHierarchyTable workflow={makeWorkflow()} readOnly />)
    fireEvent.click(screen.getByTestId('row-stepNode-step-1'))
    const state = useWorkflowStore.getState()
    expect(state.selectedNodeId).toBeNull()
    expect(state.selectedNodeType).toBeNull()
  })

  it('phase row "+ Gruppo" button opens AddGroupModal with the phaseId pre-filled and does not select the row', () => {
    renderWithQuery(<WorkflowHierarchyTable workflow={makeWorkflow()} />)
    fireEvent.click(screen.getByTestId('row-add-group-phase-1'))
    const state = useWorkflowStore.getState()
    expect(state.addGroupModal.open).toBe(true)
    expect(state.addGroupModal.phaseId).toBe('phase-1')
    // stopPropagation: row click handler must not have run
    expect(state.selectedNodeId).toBeNull()
  })

  it('group row "+ Step" button opens AddStepDialog with the groupId pre-filled', () => {
    renderWithQuery(<WorkflowHierarchyTable workflow={makeWorkflow()} />)
    fireEvent.click(screen.getByTestId('row-add-step-group-1'))
    const state = useWorkflowStore.getState()
    expect(state.addStepDialog.open).toBe(true)
    expect(state.addStepDialog.groupId).toBe('group-1')
    expect(state.selectedNodeId).toBeNull()
  })

  it('delete button opens the confirm slice with the correct nodeId + kind', () => {
    renderWithQuery(<WorkflowHierarchyTable workflow={makeWorkflow()} />)
    fireEvent.click(screen.getByTestId('row-delete-phase-1'))
    expect(useWorkflowStore.getState().deleteConfirm).toEqual({
      open: true,
      nodeId: 'phase-1',
      kind: 'phaseNode',
    })
  })

  it('readOnly mode hides the action buttons entirely', () => {
    renderWithQuery(<WorkflowHierarchyTable workflow={makeWorkflow()} readOnly />)
    expect(screen.queryByTestId('row-add-group-phase-1')).toBeNull()
    expect(screen.queryByTestId('row-edit-step-1')).toBeNull()
    expect(screen.queryByTestId('row-delete-phase-1')).toBeNull()
  })

  it('PROMPT_15 — Postazione column shows "—" when step has no workUnitId', () => {
    renderWithQuery(<WorkflowHierarchyTable workflow={makeWorkflow()} />)
    const cell = screen.getByTestId('row-postazione-step-1')
    expect(cell.textContent).toBe('—')
  })
})
