import { describe, it, expect, beforeEach, vi } from 'vitest'
import { render, screen, fireEvent } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import type { ReactNode } from 'react'
import type { WorkflowModel } from '@mes/sdk'

// PROMPT_15 C.5 — WorkflowCardView fetches the equipment tree to hydrate the
// Postazione badge. Tests mock the SDK to a flat empty tree.
vi.mock('../../lib/sdk', () => ({
  sdk: {
    equipment: { tree: vi.fn().mockResolvedValue([]) },
  },
}))

import { WorkflowCardView } from './WorkflowCardView'
import { useWorkflowStore } from './store'

function renderWithQuery(node: ReactNode) {
  const client = new QueryClient({ defaultOptions: { queries: { retry: false, gcTime: 0 } } })
  return render(<QueryClientProvider client={client}>{node}</QueryClientProvider>)
}

function makeWorkflow(): WorkflowModel {
  const meta = {
    createdAt: '2026-05-01T00:00:00.000Z',
    updatedAt: '2026-05-01T00:00:00.000Z',
    createdBy: 'system',
    updatedBy: 'system',
  }
  return {
    id: 'wf-1',
    code: 'WF-TEST',
    name: 'Test Workflow',
    plantId: 'plant-1',
    version: 1,
    ...meta,
    currentVersion: {
      id: 'wfv-1',
      workflowId: 'wf-1',
      version: 1,
      status: 'draft',
      ...meta,
      phases: [
        {
          id: 'phase-1',
          workflowVersionId: 'wfv-1',
          order: 1,
          category: 'production',
          name: 'Estrusione',
          isCycleBased: true,
          isAutoGenerated: false,
          ...meta,
          groups: [
            {
              id: 'group-1',
              phaseId: 'phase-1',
              order: 1,
              category: 'cycle',
              name: 'Estrusione PA12',
              supportsParallel: false,
              supportsRecovery: false,
              isAutoGenerated: false,
              ...meta,
              steps: [
                {
                  id: 'step-1',
                  groupId: 'group-1',
                  order: 1,
                  category: 'production',
                  actionType: 'machine_run',
                  type: 'cycle',
                  source: 'manual',
                  name: 'Avvia estrusore',
                  isRequired: true,
                  standardTimeSec: 90,
                  ...meta,
                },
              ],
            },
          ],
        },
        {
          id: 'phase-2',
          workflowVersionId: 'wfv-1',
          order: 2,
          category: 'outbound',
          name: 'Spedizione',
          isCycleBased: false,
          isAutoGenerated: false,
          ...meta,
          groups: [
            {
              id: 'group-2',
              phaseId: 'phase-2',
              order: 1,
              category: 'unloading',
              name: 'Carico bancale',
              supportsParallel: false,
              supportsRecovery: false,
              isAutoGenerated: false,
              ...meta,
              steps: [
                {
                  id: 'step-2',
                  groupId: 'group-2',
                  order: 1,
                  category: 'logistics',
                  actionType: 'manual_choice',
                  type: 'cycle',
                  source: 'manual',
                  name: 'Conferma carico',
                  isRequired: true,
                  standardTimeSec: 60,
                  ...meta,
                },
              ],
            },
          ],
        },
      ],
    },
  }
}

function resetStore() {
  useWorkflowStore.setState({
    nodes: [],
    edges: [],
    selectedNodeId: null,
    selectedNodeType: null,
    isDirty: false,
    history: { past: [], future: [] },
    dragSource: null,
    addStepDialog: {
      open: false,
      groupId: null,
      preselectedKind: null,
      preselectedCategory: null,
    },
    canvasSetNodes: null,
    triggerAutoSave: null,
    scrollToNode: null,
  })
}

describe('WorkflowCardView', () => {
  beforeEach(() => {
    resetStore()
  })

  it('renders one section per phase with all step cards inside', () => {
    renderWithQuery(<WorkflowCardView workflow={makeWorkflow()} />)
    expect(screen.getByTestId('phase-section-phase-1')).toBeInTheDocument()
    expect(screen.getByTestId('phase-section-phase-2')).toBeInTheDocument()
    expect(screen.getByTestId('card-step-step-1')).toBeInTheDocument()
    expect(screen.getByTestId('card-step-step-2')).toBeInTheDocument()
  })

  it('clicking a step card calls selectNode(stepId, "stepNode")', () => {
    renderWithQuery(<WorkflowCardView workflow={makeWorkflow()} />)
    fireEvent.click(screen.getByTestId('card-step-step-2'))
    const state = useWorkflowStore.getState()
    expect(state.selectedNodeId).toBe('step-2')
    expect(state.selectedNodeType).toBe('stepNode')
  })

  it('phase header carries the correct phase color in inline style', () => {
    renderWithQuery(<WorkflowCardView workflow={makeWorkflow()} />)
    const header = screen.getByTestId('phase-header-phase-1')
    expect(header.getAttribute('style')).toMatch(/var\(--c-production\)/)
    const header2 = screen.getByTestId('phase-header-phase-2')
    expect(header2.getAttribute('style')).toMatch(/var\(--c-outbound\)/)
  })

  it('group "+ Step" button opens AddStepDialog with the groupId pre-filled (no row select)', () => {
    renderWithQuery(<WorkflowCardView workflow={makeWorkflow()} />)
    fireEvent.click(screen.getByTestId('card-add-step-group-1'))
    const state = useWorkflowStore.getState()
    expect(state.addStepDialog.open).toBe(true)
    expect(state.addStepDialog.groupId).toBe('group-1')
    expect(state.selectedNodeId).toBeNull()
  })

  it('phase delete button opens the confirm slice for that phase', () => {
    renderWithQuery(<WorkflowCardView workflow={makeWorkflow()} />)
    fireEvent.click(screen.getByTestId('card-delete-phase-1'))
    expect(useWorkflowStore.getState().deleteConfirm).toEqual({
      open: true,
      nodeId: 'phase-1',
      kind: 'phaseNode',
    })
  })

  it('step edit button calls selectNode and stops propagation', () => {
    renderWithQuery(<WorkflowCardView workflow={makeWorkflow()} />)
    fireEvent.click(screen.getByTestId('card-edit-step-1'))
    const state = useWorkflowStore.getState()
    expect(state.selectedNodeId).toBe('step-1')
    expect(state.selectedNodeType).toBe('stepNode')
  })
})
