'use client'

import { useEffect, useRef, useState, useCallback } from 'react'
import {
  ReactFlow,
  ReactFlowProvider,
  Background,
  Controls,
  MiniMap,
  useNodesState,
  useEdgesState,
  useReactFlow,
} from '@xyflow/react'
import type { Node, Edge } from '@xyflow/react'
import type { WorkflowModel } from '@mes/sdk'
import { sdk } from '../../lib/sdk'
import { useWorkflowStore } from './store'
import { applyDagreLayout } from './layout'
import { PhaseNode } from './nodes/PhaseNode'
import { GroupNode } from './nodes/GroupNode'
import { StepNode } from './nodes/StepNode'
import { SequentialEdge } from './edges/SequentialEdge'

const nodeTypes = {
  phaseNode: PhaseNode,
  groupNode: GroupNode,
  stepNode: StepNode,
}

const edgeTypes = {
  sequential: SequentialEdge,
}

function buildGraph(workflow: WorkflowModel): { nodes: Node[]; edges: Edge[] } {
  const nodes: Node[] = []
  const edges: Edge[] = []
  const phases = workflow.currentVersion?.phases ?? []

  phases.forEach((phase, phaseIdx) => {
    nodes.push({
      id: phase.id,
      type: 'phaseNode',
      position: { x: 0, y: 0 },
      data: { label: phase.name, category: phase.category, order: phase.order },
    })

    if (phaseIdx > 0) {
      const prev = phases[phaseIdx - 1]
      if (prev) {
        edges.push({ id: `e-${prev.id}-${phase.id}`, source: prev.id, target: phase.id, type: 'sequential' })
      }
    }

    phase.groups.forEach((group, groupIdx) => {
      nodes.push({
        id: group.id,
        type: 'groupNode',
        position: { x: 0, y: 0 },
        data: { label: group.name, category: group.category, order: group.order, parentId: group.phaseId },
      })

      if (groupIdx === 0) {
        edges.push({ id: `e-${phase.id}-${group.id}`, source: phase.id, target: group.id, type: 'sequential' })
      } else {
        const prev = phase.groups[groupIdx - 1]
        if (prev) {
          edges.push({ id: `e-${prev.id}-${group.id}`, source: prev.id, target: group.id, type: 'sequential' })
        }
      }

      group.steps.forEach((step, stepIdx) => {
        nodes.push({
          id: step.id,
          type: 'stepNode',
          position: { x: 0, y: 0 },
          data: {
            label: step.name,
            category: step.category,
            actionType: step.actionType,
            type: step.type,
            source: step.source,
            instructions: step.instructions ?? '',
            skillId: step.skillId ?? '',
            deviceId: step.deviceId ?? '',
            standardTimeSec: step.standardTimeSec ?? null,
            isRequired: step.isRequired,
            order: step.order,
            parentId: step.groupId,
          },
        })

        if (stepIdx === 0) {
          edges.push({ id: `e-${group.id}-${step.id}`, source: group.id, target: step.id, type: 'sequential' })
        } else {
          const prev = group.steps[stepIdx - 1]
          if (prev) {
            edges.push({ id: `e-${prev.id}-${step.id}`, source: prev.id, target: step.id, type: 'sequential' })
          }
        }
      })
    })
  })

  return { nodes, edges }
}

// Per-category fallback action types so save never sends an empty actionType
// for a freshly dragged node that has not been opened in the configurator yet.
const DEFAULT_ACTION_TYPE: Record<string, string> = {
  production: 'assembly',
  logistics: 'move',
  identification: 'scan_qr',
  quality_control: 'visual_check',
  decision: 'manual_choice',
  information: 'read_sop',
  setup: 'verify_workstation',
  teardown: 'cleanup',
}

function buildSavePayload(nodes: Node[]) {
  const phaseNodes = nodes.filter((n) => n.type === 'phaseNode')
  return phaseNodes.map((phase) => ({
    order: phase.data.order as number,
    category: phase.data.category as string,
    name: phase.data.label as string,
    isCycleBased: false,
    isAutoGenerated: false,
    groups: nodes
      .filter((n) => n.type === 'groupNode' && n.data.parentId === phase.id)
      .map((group) => ({
        order: group.data.order as number,
        category: group.data.category as string,
        name: group.data.label as string,
        supportsParallel: false,
        supportsRecovery: false,
        isAutoGenerated: false,
        steps: nodes
          .filter((n) => n.type === 'stepNode' && n.data.parentId === group.id)
          .map((step) => {
            const category = step.data.category as string
            const actionType =
              (step.data.actionType as string | undefined) ||
              DEFAULT_ACTION_TYPE[category] ||
              'assembly'
            const instructions = step.data.instructions as string | undefined
            const skillId = step.data.skillId as string | undefined
            const deviceId = step.data.deviceId as string | undefined
            const standardTimeSec = step.data.standardTimeSec as number | null | undefined
            const isRequired =
              typeof step.data.isRequired === 'boolean' ? step.data.isRequired : true
            return {
              order: step.data.order as number,
              category,
              actionType,
              type: (step.data.type as string | undefined) ?? 'normal',
              source: (step.data.source as string | undefined) ?? 'manual',
              name: step.data.label as string,
              ...(instructions ? { instructions } : {}),
              ...(skillId ? { skillId } : {}),
              ...(deviceId ? { deviceId } : {}),
              ...(typeof standardTimeSec === 'number' ? { standardTimeSec } : {}),
              isRequired,
            }
          }),
      })),
  }))
}

type SaveStatus = 'idle' | 'saving' | 'saved'

function CanvasInner({
  workflow,
  workflowId,
  versionId,
}: {
  workflow: WorkflowModel
  workflowId: string
  versionId: string
}) {
  const { selectNode, markDirty, markClean, registerCanvasCallbacks, unregisterCanvasCallbacks } =
    useWorkflowStore()
  const { screenToFlowPosition, setCenter } = useReactFlow()
  const [nodes, setNodes, onNodesChange] = useNodesState<Node>([])
  const [edges, setEdges, onEdgesChange] = useEdgesState<Edge>([])
  const [saveStatus, setSaveStatus] = useState<SaveStatus>('idle')
  const [lastSavedAt, setLastSavedAt] = useState<string | null>(null)

  const nodesRef = useRef(nodes)
  useEffect(() => {
    nodesRef.current = nodes
  }, [nodes])

  const saveTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  const triggerAutoSave = useCallback(() => {
    if (saveTimerRef.current) clearTimeout(saveTimerRef.current)
    saveTimerRef.current = setTimeout(async () => {
      if (!versionId) return
      const payload = buildSavePayload(nodesRef.current)
      try {
        setSaveStatus('saving')
        await sdk.workflows.updateVersion(workflowId, versionId, { phases: payload })
        markClean()
        setLastSavedAt(
          new Date().toLocaleTimeString('it-IT', { hour: '2-digit', minute: '2-digit' }),
        )
        setSaveStatus('saved')
      } catch {
        setSaveStatus('idle')
      }
    }, 30_000)
  }, [workflowId, versionId, markClean])

  // Clear 'saved' indicator after 5 seconds
  useEffect(() => {
    if (saveStatus === 'saved') {
      const t = setTimeout(() => setSaveStatus('idle'), 5_000)
      return () => clearTimeout(t)
    }
  }, [saveStatus])

  const scrollToNode = useCallback(
    (nodeId: string) => {
      const target = nodesRef.current.find((n) => n.id === nodeId)
      if (!target) return
      setCenter(target.position.x, target.position.y, { zoom: 1.2, duration: 600 })
    },
    [setCenter],
  )

  // Bridge between configurator forms (which live outside this component) and
  // the canvas's local React Flow state. Forms call store.updateNodeData;
  // the store invokes these registered callbacks to mutate local nodes and
  // reset the auto-save debounce. ValidationPanel uses scrollToNode.
  useEffect(() => {
    registerCanvasCallbacks({
      setNodes: (updater) => setNodes(updater),
      triggerAutoSave,
      scrollToNode,
    })
    return () => unregisterCanvasCallbacks()
  }, [registerCanvasCallbacks, unregisterCanvasCallbacks, setNodes, triggerAutoSave, scrollToNode])

  useEffect(() => {
    const { nodes: rawNodes, edges: rawEdges } = buildGraph(workflow)
    const laid = applyDagreLayout(rawNodes, rawEdges)
    setNodes(laid)
    setEdges(rawEdges)
  }, [workflow, setNodes, setEdges])

  // Mirror local React Flow nodes into the Zustand store so the configurator
  // forms (which read selectedNodeId from the store) can resolve the selected
  // node's live data without coupling to this component's local state.
  useEffect(() => {
    useWorkflowStore.setState({ nodes })
  }, [nodes])

  const onDragOver = useCallback((event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault()
    event.dataTransfer.dropEffect = 'copy'
  }, [])

  const onDrop = useCallback(
    (event: React.DragEvent<HTMLDivElement>) => {
      event.preventDefault()
      const raw = event.dataTransfer.getData('application/workflow-node')
      if (!raw) return

      let parsed: { nodeType: string; category: string; label: string }
      try {
        parsed = JSON.parse(raw) as { nodeType: string; category: string; label: string }
      } catch {
        return
      }

      const { nodeType, category, label } = parsed
      const position = screenToFlowPosition({ x: event.clientX, y: event.clientY })
      const id = `new-${Date.now()}`

      if (nodeType === 'phaseNode') {
        const order = nodes.filter((n) => n.type === 'phaseNode').length + 1
        const newNode: Node = { id, type: 'phaseNode', position, data: { label, category, order } }
        const lastPhase = nodes.filter((n) => n.type === 'phaseNode').at(-1)
        if (lastPhase) {
          setEdges((eds) => [
            ...eds,
            { id: `e-${lastPhase.id}-${id}`, source: lastPhase.id, target: id, type: 'sequential' },
          ])
        }
        setNodes((nds) => [...nds, newNode])
      } else if (nodeType === 'groupNode') {
        const { selectedNodeId } = useWorkflowStore.getState()
        if (!selectedNodeId) return
        const order =
          nodes.filter((n) => n.type === 'groupNode' && n.data.parentId === selectedNodeId).length + 1
        const newNode: Node = {
          id,
          type: 'groupNode',
          position,
          data: { label, category, order, parentId: selectedNodeId },
        }
        setEdges((eds) => [
          ...eds,
          { id: `e-${selectedNodeId}-${id}`, source: selectedNodeId, target: id, type: 'sequential' },
        ])
        setNodes((nds) => [...nds, newNode])
      } else if (nodeType === 'stepNode') {
        const { selectedNodeId } = useWorkflowStore.getState()
        if (!selectedNodeId) return
        const order =
          nodes.filter((n) => n.type === 'stepNode' && n.data.parentId === selectedNodeId).length + 1
        const newNode: Node = {
          id,
          type: 'stepNode',
          position,
          data: { label, category, source: 'manual', standardTimeSec: null, order, parentId: selectedNodeId },
        }
        setEdges((eds) => [
          ...eds,
          { id: `e-${selectedNodeId}-${id}`, source: selectedNodeId, target: id, type: 'sequential' },
        ])
        setNodes((nds) => [...nds, newNode])
      }

      markDirty()
      triggerAutoSave()
    },
    [nodes, setNodes, setEdges, markDirty, triggerAutoSave, screenToFlowPosition],
  )

  const isEmpty = nodes.length === 0

  return (
    <div className="relative w-full h-full">
      {saveStatus !== 'idle' && (
        <div className="absolute top-2 right-2 z-10 text-[10px] text-neutral-500 bg-white/80 backdrop-blur-sm px-2 py-1 rounded shadow-sm pointer-events-none">
          {saveStatus === 'saving' && 'Salvataggio...'}
          {saveStatus === 'saved' && lastSavedAt && `Salvato alle ${lastSavedAt}`}
        </div>
      )}
      <div className="w-full h-full" onDragOver={onDragOver} onDrop={onDrop}>
        <ReactFlow
          nodes={nodes}
          edges={edges}
          onNodesChange={onNodesChange}
          onEdgesChange={onEdgesChange}
          nodeTypes={nodeTypes}
          edgeTypes={edgeTypes}
          onNodeClick={(_, node) => selectNode(node.id, node.type ?? null)}
          onPaneClick={() => selectNode(null, null)}
          fitView
        >
          <Background />
          <Controls />
          <MiniMap />
        </ReactFlow>
      </div>
      {isEmpty && (
        <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
          <p className="text-neutral-400 text-xs text-center">
            Trascina una Fase dalla palette per iniziare
          </p>
        </div>
      )}
    </div>
  )
}

export function WorkflowCanvas({ workflow }: { workflow: WorkflowModel }) {
  const versionId = workflow.currentVersion?.id ?? ''
  return (
    <ReactFlowProvider>
      <CanvasInner workflow={workflow} workflowId={workflow.id} versionId={versionId} />
    </ReactFlowProvider>
  )
}
