'use client'

import { useEffect, useRef, useState, useCallback } from 'react'
import {
  ReactFlow,
  ReactFlowProvider,
  Background,
  useNodesState,
  useEdgesState,
  useReactFlow,
  useViewport,
} from '@xyflow/react'
import type { Node, Edge } from '@xyflow/react'
import { Pencil, MousePointer2, Plus, Workflow as WorkflowIcon } from 'lucide-react'
import type { WorkflowModel } from '@mes/sdk'
import { sdk } from '../../lib/sdk'
import { useWorkflowStore } from './store'
import { applyDagreLayout } from './layout'
import { PhaseNode } from './nodes/PhaseNode'
import { GroupNode } from './nodes/GroupNode'
import { StepNode } from './nodes/StepNode'
import { SequentialEdge } from './edges/SequentialEdge'
import { CanvasContextMenu, type CanvasContextMenuState } from './CanvasContextMenu'
import { useCanvasKeyboardShortcuts } from './useCanvasKeyboardShortcuts'
import {
  CanvasToolbar,
  CanvasStateBar,
  ZoomControls,
  useToast,
} from '@mes/ui'
import {
  isStepCategoryAllowedInGroup,
  mapPaletteCategoryToStepCategory,
  type StepCategoryId,
  type StepKindId,
} from '@mes/domain'
import { applyPhaseColumnsLayout } from './canvas-layout'
import { ParallelView } from './ParallelView'

const nodeTypes = {
  phaseNode: PhaseNode,
  groupNode: GroupNode,
  stepNode: StepNode,
}

const edgeTypes = {
  sequential: SequentialEdge,
}

function buildGraph(workflow: WorkflowModel): { nodes: Node[]; edges: Edge[] } {
  const nodes: Node[] = []
  const edges: Edge[] = []
  const phases = workflow.currentVersion?.phases ?? []

  phases.forEach((phase, phaseIdx) => {
    nodes.push({
      id: phase.id,
      type: 'phaseNode',
      position: { x: 0, y: 0 },
      data: {
        label: phase.name,
        category: phase.category,
        order: phase.order,
        isCycleBased: phase.isCycleBased,
      },
    })

    if (phaseIdx > 0) {
      const prev = phases[phaseIdx - 1]
      if (prev) {
        edges.push({ id: `e-${prev.id}-${phase.id}`, source: prev.id, target: phase.id, type: 'sequential' })
      }
    }

    phase.groups.forEach((group, groupIdx) => {
      nodes.push({
        id: group.id,
        type: 'groupNode',
        position: { x: 0, y: 0 },
        data: {
          label: group.name,
          category: group.category,
          order: group.order,
          parentId: group.phaseId,
          supportsParallel: group.supportsParallel,
          supportsRecovery: group.supportsRecovery,
        },
      })

      if (groupIdx === 0) {
        edges.push({ id: `e-${phase.id}-${group.id}`, source: phase.id, target: group.id, type: 'sequential' })
      } else {
        const prev = phase.groups[groupIdx - 1]
        if (prev) {
          edges.push({ id: `e-${prev.id}-${group.id}`, source: prev.id, target: group.id, type: 'sequential' })
        }
      }

      group.steps.forEach((step, stepIdx) => {
        nodes.push({
          id: step.id,
          type: 'stepNode',
          position: { x: 0, y: 0 },
          data: {
            label: step.name,
            category: step.category,
            actionType: step.actionType,
            type: step.type,
            source: step.source,
            instructions: step.instructions ?? '',
            skillId: step.skillId ?? '',
            deviceId: step.deviceId ?? '',
            standardTimeSec: step.standardTimeSec ?? null,
            isRequired: step.isRequired,
            order: step.order,
            parentId: step.groupId,
          },
        })

        if (stepIdx === 0) {
          edges.push({ id: `e-${group.id}-${step.id}`, source: group.id, target: step.id, type: 'sequential' })
        } else {
          const prev = group.steps[stepIdx - 1]
          if (prev) {
            edges.push({ id: `e-${prev.id}-${step.id}`, source: prev.id, target: step.id, type: 'sequential' })
          }
        }
      })
    })
  })

  return { nodes, edges }
}

// Per-category fallback action types so save never sends an empty actionType
// for a freshly dragged node that has not been opened in the configurator yet.
const DEFAULT_ACTION_TYPE: Record<string, string> = {
  production: 'assembly',
  logistics: 'move',
  identification: 'scan_qr',
  quality_control: 'visual_check',
  decision: 'manual_choice',
  information: 'read_sop',
  setup: 'verify_workstation',
  teardown: 'cleanup',
  recovery: 'rework',
}

function buildSavePayload(nodes: Node[]) {
  const phaseNodes = nodes.filter((n) => n.type === 'phaseNode')
  return phaseNodes.map((phase) => ({
    order: phase.data.order as number,
    category: phase.data.category as string,
    name: phase.data.label as string,
    isCycleBased:
      typeof phase.data['isCycleBased'] === 'boolean'
        ? (phase.data['isCycleBased'] as boolean)
        : false,
    isAutoGenerated: false,
    groups: nodes
      .filter((n) => n.type === 'groupNode' && n.data.parentId === phase.id)
      .map((group) => ({
        order: group.data.order as number,
        category: group.data.category as string,
        name: group.data.label as string,
        supportsParallel:
          typeof group.data['supportsParallel'] === 'boolean'
            ? (group.data['supportsParallel'] as boolean)
            : false,
        supportsRecovery:
          typeof group.data['supportsRecovery'] === 'boolean'
            ? (group.data['supportsRecovery'] as boolean)
            : false,
        isAutoGenerated: false,
        steps: nodes
          .filter((n) => n.type === 'stepNode' && n.data.parentId === group.id)
          .map((step) => {
            const category = step.data.category as string
            const actionType =
              (step.data.actionType as string | undefined) ||
              DEFAULT_ACTION_TYPE[category] ||
              'assembly'
            const instructions = step.data.instructions as string | undefined
            const skillId = step.data.skillId as string | undefined
            const deviceId = step.data.deviceId as string | undefined
            const recipeId = step.data.recipeId as string | undefined
            const toolId = step.data.toolId as string | undefined
            // Time can land in node.data under `standardTimeSec` (existing
            // forms) or `durationSec` (AddStepDialog through PROMPT_PNE_1 D4).
            // Honor whichever is present so dialog-created steps persist their
            // standard time.
            const standardTimeSec =
              typeof step.data.standardTimeSec === 'number'
                ? (step.data.standardTimeSec as number)
                : typeof step.data.durationSec === 'number'
                  ? (step.data.durationSec as number)
                  : null
            const isRequired =
              typeof step.data.isRequired === 'boolean' ? step.data.isRequired : true
            return {
              order: step.data.order as number,
              category,
              actionType,
              type: (step.data.type as string | undefined) ?? 'normal',
              source: (step.data.source as string | undefined) ?? 'manual',
              name: step.data.label as string,
              ...(instructions ? { instructions } : {}),
              ...(skillId ? { skillId } : {}),
              ...(deviceId ? { deviceId } : {}),
              ...(recipeId ? { recipeId } : {}),
              ...(toolId ? { toolId } : {}),
              ...(typeof standardTimeSec === 'number' ? { standardTimeSec } : {}),
              isRequired,
            }
          }),
      })),
  }))
}

type SaveStatus = 'idle' | 'saving' | 'saved'

function CanvasInner({
  workflow,
  workflowId,
  versionId,
}: {
  workflow: WorkflowModel
  workflowId: string
  versionId: string
}) {
  const {
    selectNode,
    markDirty,
    markClean,
    registerCanvasCallbacks,
    unregisterCanvasCallbacks,
    openAddStepDialog,
    openAddGroupModal,
  } = useWorkflowStore()
  const toast = useToast()
  const { screenToFlowPosition, setCenter, zoomIn, zoomOut, fitView } = useReactFlow()
  const [nodes, setNodes, onNodesChange] = useNodesState<Node>([])
  const [edges, setEdges, onEdgesChange] = useEdgesState<Edge>([])
  const [saveStatus, setSaveStatus] = useState<SaveStatus>('idle')
  const [lastSavedAt, setLastSavedAt] = useState<string | null>(null)
  const [contextMenu, setContextMenu] = useState<CanvasContextMenuState | null>(null)
  const [viewMode, setViewMode] = useState<'visual' | 'parallel'>('visual')

  useCanvasKeyboardShortcuts()

  const nodesRef = useRef(nodes)
  useEffect(() => {
    nodesRef.current = nodes
  }, [nodes])

  const saveTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  const triggerAutoSave = useCallback(() => {
    if (saveTimerRef.current) clearTimeout(saveTimerRef.current)
    saveTimerRef.current = setTimeout(async () => {
      if (!versionId) return
      const payload = buildSavePayload(nodesRef.current)
      try {
        setSaveStatus('saving')
        await sdk.workflows.updateVersion(workflowId, versionId, { phases: payload })
        markClean()
        setLastSavedAt(
          new Date().toLocaleTimeString('it-IT', { hour: '2-digit', minute: '2-digit' }),
        )
        setSaveStatus('saved')
      } catch {
        setSaveStatus('idle')
      }
    }, 30_000)
  }, [workflowId, versionId, markClean])

  // Clear 'saved' indicator after 5 seconds
  useEffect(() => {
    if (saveStatus === 'saved') {
      const t = setTimeout(() => setSaveStatus('idle'), 5_000)
      return () => clearTimeout(t)
    }
  }, [saveStatus])

  const scrollToNode = useCallback(
    (nodeId: string) => {
      const target = nodesRef.current.find((n) => n.id === nodeId)
      if (!target) return
      setCenter(target.position.x, target.position.y, { zoom: 1.2, duration: 600 })
    },
    [setCenter],
  )

  // Bridge between configurator forms (which live outside this component) and
  // the canvas's local React Flow state. Forms call store.updateNodeData;
  // the store invokes these registered callbacks to mutate local nodes and
  // reset the auto-save debounce. ValidationPanel uses scrollToNode.
  useEffect(() => {
    registerCanvasCallbacks({
      setNodes: (updater) => setNodes(updater),
      triggerAutoSave,
      scrollToNode,
    })
    return () => unregisterCanvasCallbacks()
  }, [registerCanvasCallbacks, unregisterCanvasCallbacks, setNodes, triggerAutoSave, scrollToNode])

  useEffect(() => {
    const { nodes: rawNodes, edges: rawEdges } = buildGraph(workflow)
    const laid = applyPhaseColumnsLayout(rawNodes)
    setNodes(laid)
    setEdges(rawEdges)
  }, [workflow, setNodes, setEdges])

  // Mirror local React Flow nodes into the Zustand store so the configurator
  // forms (which read selectedNodeId from the store) can resolve the selected
  // node's live data without coupling to this component's local state.
  useEffect(() => {
    useWorkflowStore.setState({ nodes })
  }, [nodes])

  const onDragOver = useCallback((event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault()
    event.dataTransfer.dropEffect = 'copy'
  }, [])

  const onDrop = useCallback(
    (event: React.DragEvent<HTMLDivElement>) => {
      event.preventDefault()

      // PROMPT_3d D2 — new palette format. Drop a Step Kind / Step Category
      // onto a Group node opens the AddStepDialog.
      const paletteRaw = event.dataTransfer.getData('application/workflow-palette')
      if (paletteRaw) {
        let palette: { source: 'category' | 'kind'; id: string }
        try {
          palette = JSON.parse(paletteRaw) as { source: 'category' | 'kind'; id: string }
        } catch {
          return
        }
        const targetEl = event.target as HTMLElement | null
        const groupEl = targetEl?.closest('[data-id]') as HTMLElement | null
        const groupId = groupEl?.getAttribute('data-id') ?? null
        const groupNode = groupId
          ? nodes.find((n) => n.id === groupId && n.type === 'groupNode')
          : null
        if (!groupNode) {
          toast.show('Trascina su un gruppo per aggiungere uno step', 'info')
          return
        }
        const groupCategory = (groupNode.data['category'] as string) ?? ''
        if (palette.source === 'category') {
          const schemaCategory = mapPaletteCategoryToStepCategory(palette.id as StepCategoryId)
          if (schemaCategory && !isStepCategoryAllowedInGroup(groupCategory, schemaCategory)) {
            toast.show(
              `La categoria step non è ammessa nel gruppo "${groupCategory}"`,
              'warn',
            )
            return
          }
        }
        openAddStepDialog({
          groupId: groupNode.id,
          ...(palette.source === 'kind' ? { preselectedKind: palette.id as StepKindId } : {}),
          ...(palette.source === 'category'
            ? { preselectedCategory: palette.id as StepCategoryId }
            : {}),
        })
        return
      }

      // Legacy `application/workflow-node` format (kept for backward-compat
      // with any in-canvas drag-source that emits the old shape).
      const raw = event.dataTransfer.getData('application/workflow-node')
      if (!raw) return

      let parsed: { nodeType: string; category: string; label: string }
      try {
        parsed = JSON.parse(raw) as { nodeType: string; category: string; label: string }
      } catch {
        return
      }

      const { nodeType, category, label } = parsed
      const position = screenToFlowPosition({ x: event.clientX, y: event.clientY })
      const id = `new-${Date.now()}`

      if (nodeType === 'phaseNode') {
        const order = nodes.filter((n) => n.type === 'phaseNode').length + 1
        const newNode: Node = { id, type: 'phaseNode', position, data: { label, category, order } }
        const lastPhase = nodes.filter((n) => n.type === 'phaseNode').at(-1)
        if (lastPhase) {
          setEdges((eds) => [
            ...eds,
            { id: `e-${lastPhase.id}-${id}`, source: lastPhase.id, target: id, type: 'sequential' },
          ])
        }
        setNodes((nds) => [...nds, newNode])
      } else if (nodeType === 'groupNode') {
        const { selectedNodeId } = useWorkflowStore.getState()
        if (!selectedNodeId) return
        const order =
          nodes.filter((n) => n.type === 'groupNode' && n.data.parentId === selectedNodeId).length + 1
        const newNode: Node = {
          id,
          type: 'groupNode',
          position,
          data: { label, category, order, parentId: selectedNodeId },
        }
        setEdges((eds) => [
          ...eds,
          { id: `e-${selectedNodeId}-${id}`, source: selectedNodeId, target: id, type: 'sequential' },
        ])
        setNodes((nds) => [...nds, newNode])
      } else if (nodeType === 'stepNode') {
        const { selectedNodeId } = useWorkflowStore.getState()
        if (!selectedNodeId) return
        const order =
          nodes.filter((n) => n.type === 'stepNode' && n.data.parentId === selectedNodeId).length + 1
        const newNode: Node = {
          id,
          type: 'stepNode',
          position,
          data: { label, category, source: 'manual', standardTimeSec: null, order, parentId: selectedNodeId },
        }
        setEdges((eds) => [
          ...eds,
          { id: `e-${selectedNodeId}-${id}`, source: selectedNodeId, target: id, type: 'sequential' },
        ])
        setNodes((nds) => [...nds, newNode])
      }

      markDirty()
      triggerAutoSave()
    },
    [
      nodes,
      setNodes,
      setEdges,
      markDirty,
      triggerAutoSave,
      screenToFlowPosition,
      openAddStepDialog,
      toast,
    ],
  )

  const isEmpty = nodes.length === 0
  const { zoom } = useViewport()
  const zoomPercent = Math.round(zoom * 100)
  const isDirty = useWorkflowStore((s) => s.isDirty)

  const stateBarTone: 'ok' | 'warn' | 'neutral' =
    saveStatus === 'saving'
      ? 'warn'
      : saveStatus === 'saved'
        ? 'ok'
        : isDirty
          ? 'warn'
          : 'neutral'
  const stateBarStatus =
    saveStatus === 'saving'
      ? 'Salvataggio…'
      : saveStatus === 'saved' && lastSavedAt
        ? `Salvato ${lastSavedAt}`
        : isDirty
          ? 'Modifiche non salvate'
          : 'Nessuna modifica'
  const stepCount = nodes.filter((n) => n.type === 'stepNode').length
  const counts = `${nodes.length} nodi · ${edges.length} archi · ${stepCount} step`

  const toolbarTools = [
    { id: 'select', icon: MousePointer2, label: 'Seleziona', active: true },
    {
      id: 'pan',
      icon: WorkflowIcon,
      label: 'Pan',
      onClick: () => {
        // React Flow pan is on by default with middle-mouse / space — this
        // toggle is a placeholder for an explicit pan mode in F2.
      },
    },
    {
      id: 'add',
      icon: Plus,
      label: 'Aggiungi',
      onClick: () => {
        toast.show('Aggiungi: usa il pulsante "Aggiungi Fase" sul topbar (D5)', 'info')
      },
    },
    {
      id: 'annotate',
      icon: Pencil,
      label: 'Annota',
      onClick: () => {
        toast.show('Annotazioni — disponibile in F2', 'info')
      },
    },
  ]

  return (
    <div className="relative w-full h-full">
      <div
        className="absolute top-3 left-1/2 z-10 -translate-x-1/2 inline-flex rounded-1 border border-line bg-paper p-0.5 text-xs"
        role="tablist"
        aria-label="Modalità canvas"
        data-canvas-view-toggle
      >
        <button
          type="button"
          role="tab"
          aria-selected={viewMode === 'visual'}
          onClick={() => setViewMode('visual')}
          className={
            'rounded-1 px-3 py-1 font-medium transition-colors ' +
            (viewMode === 'visual'
              ? 'bg-accent text-white'
              : 'text-ink-3 hover:text-ink')
          }
        >
          Visual Editor
        </button>
        <button
          type="button"
          role="tab"
          aria-selected={viewMode === 'parallel'}
          onClick={() => setViewMode('parallel')}
          className={
            'rounded-1 px-3 py-1 font-medium transition-colors ' +
            (viewMode === 'parallel'
              ? 'bg-accent text-white'
              : 'text-ink-3 hover:text-ink')
          }
        >
          Parallel
        </button>
      </div>
      {viewMode === 'parallel' ? (
        <ParallelView />
      ) : (
      <div
        className="w-full h-full"
        onDragOver={onDragOver}
        onDrop={onDrop}
        data-canvas="phase-columns"
      >
        <ReactFlow
          nodes={nodes}
          edges={edges}
          onNodesChange={onNodesChange}
          onEdgesChange={onEdgesChange}
          nodeTypes={nodeTypes}
          edgeTypes={edgeTypes}
          onNodeClick={(_, node) => selectNode(node.id, node.type ?? null)}
          onPaneClick={() => {
            selectNode(null, null)
            setContextMenu(null)
          }}
          onNodeContextMenu={(event, node) => {
            event.preventDefault()
            selectNode(node.id, node.type ?? null)
            setContextMenu({
              x: event.clientX,
              y: event.clientY,
              nodeId: node.id,
              nodeType: node.type ?? '',
            })
          }}
          fitView
          minZoom={0.25}
          maxZoom={2}
        >
          <Background gap={16} size={0.6} color="var(--ink-3)" />
        </ReactFlow>
      </div>
      )}
      {viewMode === 'visual' && (
        <>
          <CanvasToolbar tools={toolbarTools} />
          <CanvasStateBar tone={stateBarTone} status={stateBarStatus} counts={counts} />
          <ZoomControls
            zoomPercent={zoomPercent}
            onZoomIn={() => zoomIn()}
            onZoomOut={() => zoomOut()}
            onFit={() => fitView()}
          />
          <CanvasContextMenu
            state={contextMenu}
            onClose={() => setContextMenu(null)}
            onAddGroupRequested={(phaseId) => openAddGroupModal(phaseId)}
          />
          {isEmpty && (
            <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
              <p className="text-neutral-400 text-xs text-center">
                Aggiungi una Fase dal topbar per iniziare
              </p>
            </div>
          )}
        </>
      )}
    </div>
  )
}

export function WorkflowCanvas({ workflow }: { workflow: WorkflowModel }) {
  const versionId = workflow.currentVersion?.id ?? ''
  return (
    <ReactFlowProvider>
      <CanvasInner workflow={workflow} workflowId={workflow.id} versionId={versionId} />
    </ReactFlowProvider>
  )
}
